variables:
  #year: "2025"
  #month: "09"
  #download_url: "https://common-lisp.net/project/cmucl/downloads/snapshots/$year/$month"
  #version: "$year-$month-x86"
  release: "21f"
  download_url: "https://common-lisp.net/project/cmucl/downloads/release/$release"
  version: "$release-x86"
  tar_ext: "xz"
  bootstrap: ""

workflow:
  rules:
    # Always run on schedules (for analyze and markdown-link-check stages)
    - if: $CI_PIPELINE_SOURCE == "schedule"
    # Run on merge requests
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    # Don't create a branch pipeline when an MR pipeline already exists
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_TAG

.install_template: &install_configuration
  stage: install
  artifacts:
    paths:
      - snapshot/
  script:
    - echo PATH = $PATH
    - ls -F /usr/local/bin
    - type -all gitlab-runner
    - $CURL -o cmucl-$version-$osname.tar.$tar_ext $download_url/cmucl-$version-$osname.tar.$tar_ext
    - $CURL -o cmucl-$version-$osname.extra.tar.$tar_ext $download_url/cmucl-$version-$osname.extra.tar.$tar_ext
    - mkdir snapshot
    - (cd snapshot; tar xf ../cmucl-$version-$osname.tar.$tar_ext; tar xf ../cmucl-$version-$osname.extra.tar.$tar_ext)

.build_template: &build_configuration
  stage: build
  artifacts:
    paths:
      - dist/
      - build-2/*.log
      - build-3/*.log
      - build-4/
      - cmucl*
      - src/lisp/cmucl-version.h
      - src/code/errno.lisp
  script:
    - bin/build.sh $bootstrap -b build -R -C $CONFIG -o snapshot/bin/lisp
    - sh -x bin/git-version.sh
    - bin/make-dist.sh -I dist build-4
    - bin/make-dist.sh -S build-4

.ansi_test_template: &ansi_test_configuration
  stage: ansi-test
  artifacts:
    paths:
      - ansi-test.out
  script:
    - bin/run-ansi-tests.sh -l dist/bin/lisp
    - cp ../ansi-test/test.out ansi-test.out

.unit_test_template: &unit_test_configuration
  stage: test
  artifacts:
    paths:
      - test.log
  script:
    - echo LANG = $LANG
    - bin/run-unit-tests.sh -l dist/bin/lisp 2>&1 | tee test.log

.exec_test_template: &exec_test_configuration
  stage: test
  script:
    - dist/bin/lisp -eval '(save-lisp "saved-lisp-executable" :executable t)'
    - ./saved-lisp-executable --version
    - bin/run-unit-tests.sh -l ./saved-lisp-executable

.benchmark_template: &benchmark_configuration
  stage: benchmark
  artifacts:
    paths:
      - benchmarks/cl-bench/results
  script:
    - cd benchmarks/cl-bench
    - mkdir tmp
    - CMUCL=../../snapshot/bin/lisp ./run-cmucl.sh
    - CMUCL=../../dist/bin/lisp ./run-cmucl.sh
    - ../../snapshot/bin/lisp -load report

stages:
  - install
  - build
  - test
  - ansi-test
  - benchmark
  - analyze
  - markdown-link-check

cache:

#### Linux jobs ####
linux:install:
  <<: *install_configuration
  tags:
    - linux
  variables:
    osname: "linux"
    CURL: "curl"

linux:build:
  <<: *build_configuration
  tags:
    - linux
  needs:
    - job: linux:install
      artifacts: true
  variables:
    CONFIG: "x86_linux"

linux:cross-build:
  stage: build
  tags:
    - linux
  artifacts:
    paths:
      - xdist/
      - linux-2/*.log
      - linux-3/*.log
      - linux-4/*.log
      - linux-4/lisp
  variables:
    CONFIG: "x86_linux"
  needs:
    - job: linux:build
      artifacts: true
  script:
    - bin/create-target.sh xtarget $CONFIG
    - bin/create-target.sh xcross $CONFIG
    - bin/cross-build-world.sh -crl xtarget xcross src/tools/cross-scripts/cross-x86-x86.lisp dist/bin/lisp
    - bin/build.sh -b xlinux $bootstrap -R -C $CONFIG -o "xtarget/lisp/lisp -lib xtarget/lisp"
    - bin/make-dist.sh -I xdist xlinux-4

linux:test:
  <<: *unit_test_configuration
  tags:
    - linux
  needs:
    - job: linux:build
      artifacts: true

linux:exec-test:
  <<: *exec_test_configuration
  tags:
    - linux
  needs:
    - job: linux:build
      artifacts: true

linux:cross-test:
  stage: test
  tags:
    - linux
  artifacts:
    paths:
      - ansi-test/test.out
      - cross-test.log
  needs:
    - job: linux:cross-build
      artifacts: true
  script:
    - bin/run-unit-tests.sh -l xdist/bin/lisp 2>&1 | tee cross-test.log

linux:ansi-test:
  <<: *ansi_test_configuration
  tags:
    - linux
  needs:
    - job: linux:build
      artifacts: true

linux:benchmark:
  <<: *benchmark_configuration
  tags:
    - linux
  needs:
    - job: linux:install
      artifacts: true
    - job: linux:build

#### OSX (Mac) jobs ####
osx:install:
  <<: *install_configuration
  tags:
    - macos-virtualbox
  variables:
    osname: "darwin"
    CURL: "/opt/local/bin/curl"

osx:build:
  <<: *build_configuration
  tags:
    - macos-virtualbox
  needs:
    - job: osx:install
      artifacts: true
  variables:
    CONFIG: "x86_darwin"

osx:test:
  <<: *unit_test_configuration
  tags:
    - macos-virtualbox
  needs:
    - job: osx:build
      artifacts: true

osx:exec-test:
  <<: *exec_test_configuration
  tags:
    - macos-virtualbox
  needs:
    - job: osx:build
      artifacts: true

osx:ansi-test:
  <<: *ansi_test_configuration
  tags:
    - macos-virtualbox
  needs:
    - job: osx:build
      artifacts: true

osx:benchmark:
  <<: *benchmark_configuration
  tags:
    - macos-virtualbox
  needs:
    - job: osx:install
      artifacts: true
    - job: osx:build

#### OpenSUSE jobs ####
ubuntu:install:
  <<: *install_configuration
  tags:
    - ubuntu
  variables:
    osname: "linux"
    CURL: "curl"

ubuntu:build:
  <<: *build_configuration
  tags:
    - ubuntu
  needs:
    - job: ubuntu:install
      artifacts: true
  variables:
    CONFIG: "x86_linux"

ubuntu:test:
  <<: *unit_test_configuration
  tags:
    - ubuntu
  needs:
    - job: ubuntu:build
      artifacts: true

ubuntu:ansi-test:
  <<: *ansi_test_configuration
  tags:
    - ubuntu
  needs:
    - job: ubuntu:build
      artifacts: true

linux:static-analyzer:
  stage: analyze
  tags:
    - linux
  artifacts:
    when: always
    paths:
      - analyzer.log
  needs:
    - job: linux:build
      artifacts: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - when: manual
      allow_failure: true
  script:
    - make -C build-4/lisp clean
    - make -C build-4/lisp ANALYZER=-fanalyzer > analyzer.log 2>&1

markdown-link-check:
  stage: markdown-link-check
  tags:
    - linux
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - when: manual
      allow_failure: true
  script:
    - find . -name \*.md -print0 | xargs -0 -n1 markdown-link-check
    - git clone https://gitlab.common-lisp.net/cmucl/cmucl.wiki.git
    - find cmucl.wiki -name \*.md -print0 | xargs -0 -n1 markdown-link-check

