
(IN-PACKAGE "USER") 
(PROCLAIM '(FTYPE (FUNCTION (*) FIXNUM) PCL::ZERO)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T FIXNUM *) FIXNUM)
            PCL::COMPUTE-PRIMARY-CACHE-LOCATION-FROM-LOCATION)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) FUNCTION) PCL::CACHE-LIMIT-FN
            PCL::METHOD-CALL-FUNCTION PCL::FAST-METHOD-CALL-FUNCTION)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) FIXNUM) PCL::DEFAULT-LIMIT-FN
            PCL::PV-CACHE-LIMIT-FN PCL::CACHE-COUNT
            PCL::ARG-INFO-NUMBER-REQUIRED PCL::ONE-INDEX-LIMIT-FN
            PCL::N-N-ACCESSORS-LIMIT-FN PCL::CHECKING-LIMIT-FN
            PCL::CACHING-LIMIT-FN PCL::CACHE-NLINES
            PCL::CACHE-MAX-LOCATION PCL::CACHE-SIZE PCL::CACHE-MASK
            PCL::PV-TABLE-PV-SIZE PCL::FAST-INSTANCE-BOUNDP-INDEX
            PCL::EARLY-CLASS-SIZE)) 
(PROCLAIM '(FTYPE (FUNCTION (T) PCL::FIELD-TYPE) PCL::CACHE-FIELD)) 
(PROCLAIM '(FTYPE (FUNCTION (FIXNUM) T) PCL::POWER-OF-TWO-CEILING)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) LIST) PCL::CACHE-OVERFLOW
            PCL::PV-TABLE-SLOT-NAME-LISTS PCL::PV-TABLE-CALL-LIST)) 
(PROCLAIM '(FTYPE (FUNCTION (T) (MEMBER NIL T)) PCL::CACHE-VALUEP)) 
(PROCLAIM '(FTYPE (FUNCTION (T) SIMPLE-VECTOR) PCL::CACHE-VECTOR)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) (VALUES T T)) PCL::MAKE-CLASS-PREDICATE-NAME
            PCL::MAKE-KEYWORD)) 
(PROCLAIM '(FTYPE (FUNCTION (FIXNUM T) T) PCL::%CCLOSURE-ENV-NTHCDR)) 
(PROCLAIM
    '(FTYPE (FUNCTION (FIXNUM FIXNUM T) FIXNUM)
            PCL::COMPUTE-PRIMARY-CACHE-LOCATION)) 
(PROCLAIM '(FTYPE (FUNCTION (T) (INTEGER 1 512)) PCL::CACHE-LINE-SIZE)) 
(PROCLAIM '(FTYPE (FUNCTION (T) (INTEGER 1 256)) PCL::CACHE-NKEYS)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) (OR PCL::CACHE NULL)) PCL::PV-TABLE-CACHE)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T) *) PCL::OPTIMIZE-SLOT-VALUE-BY-CLASS-P
            PCL::ACCESSOR-VALUES1 WALKER::WALK-LET-IF
            PCL::EMIT-READER/WRITER
            PCL::EMIT-ONE-OR-N-INDEX-READER/WRITER PCL::GENERATING-LISP
            PCL::SET-SLOT-VALUE PCL::EMIT-READER/WRITER-FUNCTION
            PCL::EMIT-ONE-OR-N-INDEX-READER/WRITER-FUNCTION
            PCL::ACCESSOR-VALUES-INTERNAL PCL::CONVERT-METHODS
            PCL::|(FAST-METHOD COMPUTE-DISCRIMINATING-FUNCTION-ARGLIST-INFO
    (STANDARD-GENERIC-FUNCTION))| PCL::SLOT-VALUE-USING-CLASS-DFUN
            PCL::SLOT-BOUNDP-USING-CLASS-DFUN PCL::LOAD-LONG-DEFCOMBIN
            PCL::CACHE-MISS-VALUES
            PCL::|(FAST-METHOD METHOD-FUNCTION (STANDARD-METHOD))|
            PCL::|(FAST-METHOD COMPUTE-DISCRIMINATING-FUNCTION
    (STANDARD-GENERIC-FUNCTION))|
            PCL::|(FAST-METHOD FUNCTION-KEYWORDS (STANDARD-METHOD))|
            PCL::|(FAST-METHOD METHOD-PRETTY-ARGLIST (STANDARD-METHOD))|
            PCL::GET-CLASS-SLOT-VALUE-1 ITERATE::EXPAND-INTO-LET
            WALKER::WALK-FORM-INTERNAL ITERATE::RENAME-VARIABLES
            PCL::ACCESSOR-VALUES ITERATE::WALK-GATHERING-BODY
            PCL::MAKE-OPTIMIZED-STD-READER-METHOD-FUNCTION
            PCL::MAKE-OPTIMIZED-STD-WRITER-METHOD-FUNCTION
            PCL::MAKE-OPTIMIZED-STD-BOUNDP-METHOD-FUNCTION
            PCL::CONSTANT-VALUE-MISS PCL::CACHING-MISS
            PCL::CHECKING-MISS
            PCL::GET-OPTIMIZED-STD-ACCESSOR-METHOD-FUNCTION
            PCL::GET-OPTIMIZED-STD-SLOT-VALUE-USING-CLASS-METHOD-FUNCTION
            PCL::|(FAST-METHOD CLASS-PROTOTYPE (STD-CLASS))|
            PCL::|(FAST-METHOD CLASS-PROTOTYPE (STRUCTURE-CLASS))|
            PCL::|(FAST-METHOD METHOD-LAMBDA-LIST (TRACED-METHOD))|
            PCL::|(FAST-METHOD METHOD-SPECIALIZERS (TRACED-METHOD))|
            PCL::|(FAST-METHOD METHOD-QUALIFIERS (TRACED-METHOD))|
            PCL::|(FAST-METHOD ACCESSOR-METHOD-SLOT-NAME (TRACED-METHOD))|
            PCL::MAKE-FINAL-N-N-ACCESSOR-DFUN
            PCL::MAKE-FINAL-CACHING-DFUN
            PCL::MAKE-FINAL-CONSTANT-VALUE-DFUN
            PCL::|(FAST-METHOD MAKE-INSTANCES-OBSOLETE (SYMBOL))|)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T) *) PCL::REAL-MAKE-METHOD-LAMBDA
            PCL::|(FAST-METHOD CHANGE-CLASS (T SYMBOL))|
            PCL::GET-ACCESSOR-METHOD-FUNCTION
            PCL::EMIT-CHECKING-OR-CACHING
            PCL::|(FAST-METHOD REINITIALIZE-INSTANCE :AFTER (SLOT-CLASS))|
            PCL::BOOTSTRAP-ACCESSOR-DEFINITION
            PCL::EMIT-CHECKING-OR-CACHING-FUNCTION
            PCL::|(FAST-METHOD NO-APPLICABLE-METHOD (T))|
            PCL::|(FAST-METHOD SLOT-ACCESSOR-FUNCTION (EFFECTIVE-SLOT-DEFINITION T))|
            PCL::|(FAST-METHOD COMPUTE-EFFECTIVE-SLOT-DEFINITION (SLOT-CLASS T))|
            PCL::|(FAST-METHOD LEGAL-QUALIFIERS-P (STANDARD-METHOD T))|
            PCL::|(FAST-METHOD LEGAL-SPECIALIZERS-P (STANDARD-METHOD T))|
            PCL::SETF-SLOT-VALUE-USING-CLASS-DFUN
            PCL::LOAD-SHORT-DEFCOMBIN
            PCL::|(FAST-METHOD COMPUTE-APPLICABLE-METHODS-USING-CLASSES
    (GENERIC-FUNCTION T))| PCL::SET-CLASS-SLOT-VALUE-1
            PCL::MAKE-SHARED-INITIALIZE-FORM-LIST
            PCL::|(FAST-METHOD CLASS-SLOT-VALUE (STD-CLASS T))|
            PCL::GENERATE-DISCRIMINATION-NET PCL::ORDER-SPECIALIZERS
            PCL::MAKE-ONE-CLASS-ACCESSOR-DFUN PCL::ACCESSOR-MISS
            PCL::|(FAST-METHOD ALLOCATE-INSTANCE (STRUCTURE-CLASS))|
            PCL::GET-ACCESSOR-FROM-SVUC-METHOD-FUNCTION
            PCL::|(FAST-METHOD DESCRIBE-OBJECT (T T))|
            PCL::|(FAST-METHOD DOCUMENTATION (STANDARD-SLOT-DEFINITION))|
            PCL::|(FAST-METHOD DESCRIBE-OBJECT (SLOT-OBJECT T))|
            PCL::|(FAST-METHOD SLOTS-TO-INSPECT (SLOT-CLASS SLOT-OBJECT))|
            PCL::|(FAST-METHOD DESCRIBE-OBJECT (STANDARD-GENERIC-FUNCTION T))|
            PCL::|(FAST-METHOD DESCRIBE-OBJECT (CLASS T))|
            PCL::|(FAST-METHOD MAKE-INSTANCE (SYMBOL))|
            PCL::|(FAST-METHOD DEFAULT-INITARGS (SLOT-CLASS T))|
            PCL::|(FAST-METHOD INITIALIZE-INSTANCE (SLOT-OBJECT))|
            PCL::|(FAST-METHOD MAYBE-UPDATE-CONSTRUCTORS (GENERIC-FUNCTION METHOD))|
            PCL::MAKE-FINAL-ONE-INDEX-ACCESSOR-DFUN
            PCL::MAKE-FINAL-CHECKING-DFUN)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T) *)
            PCL::|(FAST-METHOD SHARED-INITIALIZE :AFTER (CLASS-EQ-SPECIALIZER T))|
            PCL::|(FAST-METHOD SHARED-INITIALIZE :AFTER (EQL-SPECIALIZER T))|
            PCL::|(FAST-METHOD SHARED-INITIALIZE :BEFORE (CLASS T))|
            PCL::ADD-METHOD-DECLARATIONS PCL::WALK-METHOD-LAMBDA
            PCL::|(FAST-METHOD (SETF SLOT-ACCESSOR-FUNCTION)
    (T EFFECTIVE-SLOT-DEFINITION T))|
            PCL::|(FAST-METHOD SHARED-INITIALIZE :BEFORE (STANDARD-METHOD T))|
            PCL::|(FAST-METHOD SHARED-INITIALIZE :AFTER (STANDARD-ACCESSOR-METHOD T))|
            PCL::|(FAST-METHOD SHARED-INITIALIZE :BEFORE (STANDARD-GENERIC-FUNCTION T))|
            PCL::COMPUTE-DISCRIMINATING-FUNCTION-ARGLIST-INFO-INTERNAL
            PCL::|(FAST-METHOD SHARED-INITIALIZE :AFTER (STANDARD-SLOT-DEFINITION T))|
            PCL::|(FAST-METHOD (SETF CLASS-SLOT-VALUE) (T STD-CLASS T))|
            PCL::|(FAST-METHOD SLOT-VALUE-USING-CLASS
    (STD-CLASS STANDARD-OBJECT STANDARD-EFFECTIVE-SLOT-DEFINITION))|
            PCL::MAKE-TWO-CLASS-ACCESSOR-DFUN
            PCL::|(FAST-METHOD SLOT-VALUE-USING-CLASS
    (STRUCTURE-CLASS STRUCTURE-OBJECT
        STRUCTURE-EFFECTIVE-SLOT-DEFINITION))|
            PCL::|(FAST-METHOD COMPUTE-EFFECTIVE-METHOD
    (GENERIC-FUNCTION LONG-METHOD-COMBINATION T))|
            PCL::|(FAST-METHOD (SETF DOCUMENTATION) (T STANDARD-SLOT-DEFINITION))|
            PCL::|(FAST-METHOD ADD-READER-METHOD (SLOT-CLASS T T))|
            PCL::|(FAST-METHOD ADD-WRITER-METHOD (SLOT-CLASS T T))|
            PCL::|(FAST-METHOD ADD-BOUNDP-METHOD (SLOT-CLASS T T))|
            PCL::|(FAST-METHOD UPDATE-INSTANCE-FOR-DIFFERENT-CLASS
    (STANDARD-OBJECT STANDARD-OBJECT))|
            PCL::|(FAST-METHOD SHARED-INITIALIZE (SLOT-OBJECT T))|)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T *) *) PCL::TYPES-FROM-ARGUMENTS
            PCL::MAKE-ACCESSOR-TABLE
            PCL::COMPUTE-SECONDARY-DISPATCH-FUNCTION
            PCL::GET-SIMPLE-INITIALIZATION-FUNCTION
            PCL::GET-COMPLEX-INITIALIZATION-FUNCTIONS
            PCL::MAKE-CHECKING-DFUN
            PCL::MAKE-DEFAULT-INITARGS-FORM-LIST
            PCL::SLOT-VALUE-OR-DEFAULT PCL::MAKE-N-N-ACCESSOR-DFUN
            PCL::GET-EFFECTIVE-METHOD-FUNCTION PCL::LOAD-DEFGENERIC
            PCL::MAKE-EFFECTIVE-METHOD-FUNCTION
            WALKER:NESTED-WALK-FORM)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T T) *)
            ITERATE::ITERATE-TRANSFORM-BODY
            PCL::|(FAST-METHOD UPDATE-INSTANCE-FOR-REDEFINED-CLASS
    (STANDARD-OBJECT T T T))|)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T *) *) PCL::REAL-MAKE-A-METHOD)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T) *) PCL::REAL-LOAD-DEFCLASS
            PCL::CACHE-MISS-VALUES-INTERNAL
            PCL::GENERATE-DISCRIMINATION-NET-INTERNAL
            PCL::|(FAST-METHOD (SETF SLOT-VALUE-USING-CLASS)
    (T STRUCTURE-CLASS STRUCTURE-OBJECT
       STRUCTURE-EFFECTIVE-SLOT-DEFINITION))|
            PCL::MAKE-LONG-METHOD-COMBINATION-FUNCTION
            PCL::DO-SHORT-METHOD-COMBINATION PCL::MEMF-CODE-CONVERTER)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T *) *) ITERATE::RENAME-LET-BINDINGS
            PCL::MAKE-EFFECTIVE-METHOD-FUNCTION-SIMPLE1)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T *) *) WALKER::WALK-DECLARATIONS
            PCL::MAKE-ONE-INDEX-ACCESSOR-DFUN
            PCL::GET-SECONDARY-DISPATCH-FUNCTION)) 
(PROCLAIM '(FTYPE (FUNCTION (T STREAM T) T) PCL::PRINT-DFUN-INFO)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T *) T) PCL::CPL-ERROR
            PCL::METHOD-FUNCTION-GET
            PCL:ENSURE-GENERIC-FUNCTION-USING-CLASS
            PCL::GET-CACHE-FROM-CACHE PCL::EMIT-MISS
            PCL::GET-METHOD-FUNCTION-PV-CELL
            PCL::NAMED-OBJECT-PRINT-FUNCTION PCL::RECORD-DEFINITION
            WALKER::CONVERT-MACRO-TO-LAMBDA
            PCL::PRECOMPUTE-EFFECTIVE-METHODS
            PCL::COMPUTE-SECONDARY-DISPATCH-FUNCTION1 PCL::PROBE-CACHE
            PCL::MAP-CACHE PCL::INITIALIZE-INFO
            PCL::GET-EFFECTIVE-METHOD-FUNCTION1
            PCL::MAKE-EFFECTIVE-METHOD-FUNCTION-SIMPLE
            PCL::MAKE-EMF-FROM-METHOD
            PCL::EXPAND-EFFECTIVE-METHOD-FUNCTION
            PCL::FIND-CLASS-FROM-CELL PCL::REAL-ADD-METHOD
            PCL::FIND-CLASS-PREDICATE-FROM-CELL PCL::GET-DECLARATION
            PCL::REAL-ENSURE-GF-USING-CLASS--GENERIC-FUNCTION
            PCL::REAL-ENSURE-GF-USING-CLASS--NULL)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T) T) PCL::GET-NEW-FUNCTION-GENERATOR
            PCL::|(FAST-METHOD SPECIALIZER-METHOD-TABLE (EQL-SPECIALIZER))|
            PCL::|(FAST-METHOD SPECIALIZER-METHOD-TABLE (CLASS-EQ-SPECIALIZER))|
            WALKER::WALK-TAGBODY-1 PCL::NOTE-PV-TABLE-REFERENCE
            WALKER::WALK-LAMBDA
            PCL::|(FAST-METHOD SPECIALIZER-DIRECT-METHODS (SPECIALIZER-WITH-OBJECT))|
            PCL::|(FAST-METHOD SPECIALIZER-DIRECT-GENERIC-FUNCTIONS
    (SPECIALIZER-WITH-OBJECT))| WALKER::WALK-COMPILER-LET
            PCL::|(FAST-METHOD CLASS-DIRECT-SLOTS (BUILT-IN-CLASS))|
            WALKER::WALK-UNEXPECTED-DECLARE WALKER::WALK-FLET
            PCL::|(FAST-METHOD CLASS-SLOTS (BUILT-IN-CLASS))|
            WALKER::WALK-IF WALKER::WALK-LABELS WALKER::WALK-LET
            PCL::|(FAST-METHOD CLASS-DIRECT-DEFAULT-INITARGS (BUILT-IN-CLASS))|
            PCL::FLUSH-CACHE-TRAP WALKER::WALK-LET*
            PCL::OBSOLETE-INSTANCE-TRAP WALKER::WALK-MACROLET
            WALKER::WALK-MULTIPLE-VALUE-SETQ
            PCL::|(FAST-METHOD CLASS-DEFAULT-INITARGS (BUILT-IN-CLASS))|
            WALKER::WALK-MULTIPLE-VALUE-BIND WALKER::WALK-SETQ
            WALKER::WALK-SYMBOL-MACROLET WALKER::WALK-TAGBODY
            WALKER::WALK-DO WALKER::WALK-DO* WALKER::WALK-PROG
            WALKER::WALK-PROG* WALKER::WALK-NAMED-LAMBDA
            PCL::OPTIMIZE-GF-CALL-INTERNAL PCL::SKIP-FAST-SLOT-ACCESS-P
            PCL::SKIP-OPTIMIZE-SLOT-VALUE-BY-CLASS-P
            PCL::EXPAND-DEFGENERIC
            PCL::|(FAST-METHOD RAW-INSTANCE-ALLOCATOR (FUNCALLABLE-STANDARD-CLASS))|
            PCL::EMIT-SLOT-READ-FORM PCL::EMIT-BOUNDP-CHECK
            PCL::FIX-SLOT-ACCESSORS
            PCL::MAKE-METHOD-INITARGS-FORM-INTERNAL
            PCL::|(FAST-METHOD FINALIZE-INHERITANCE (STRUCTURE-CLASS))|
            PCL::EMIT-GREATER-THAN-1-DLAP
            PCL::|(FAST-METHOD FINALIZE-INHERITANCE (STD-CLASS))|
            PCL::EMIT-1-T-DLAP
            PCL::|(FAST-METHOD COMPUTE-DEFAULT-INITARGS (SLOT-CLASS))|
            PCL::|(FAST-METHOD WRAPPER-FETCHER (FUNCALLABLE-STANDARD-CLASS))|
            PCL::|(FAST-METHOD COMPUTE-SLOTS (STD-CLASS))|
            PCL::|(FAST-METHOD COMPUTE-SLOTS :AROUND (STD-CLASS))|
            PCL::|(FAST-METHOD COMPUTE-SLOTS (STRUCTURE-CLASS))|
            PCL::|(FAST-METHOD COMPUTE-SLOTS :AROUND (STRUCTURE-CLASS))|
            PCL::|(FAST-METHOD SLOTS-FETCHER (FUNCALLABLE-STANDARD-CLASS))|
            PCL::MAKE-METHOD-SPEC
            PCL::NEW-ARG-INFO-FROM-GENERIC-FUNCTION PCL::PRINT-CACHE
            PCL::SET-FUNCTION-NAME-1
            PCL::|(FAST-METHOD METHOD-QUALIFIERS (STANDARD-METHOD))|
            PCL::|SETF PCL METHOD-FUNCTION-GET| PCL::INVALIDATE-WRAPPER
            PCL::PRINT-STD-INSTANCE PCL::|SETF PCL PLIST-VALUE|
            PCL::TRACE-METHOD-INTERNAL PCL::ONE-INDEX-DFUN-INFO
            PCL::|(FAST-METHOD GENERIC-FUNCTION-LAMBDA-LIST (GENERIC-FUNCTION))|
            PCL::|(FAST-METHOD GF-FAST-METHOD-FUNCTION-P (STANDARD-GENERIC-FUNCTION))|
            PCL::CONVERT-TABLE
            PCL::|(FAST-METHOD SPECIALIZER-CLASS (CLASS))|
            PCL::DECLARE-STRUCTURE PCL::LOAD-PRECOMPILED-IIS-ENTRY
            PCL::|(FAST-METHOD SPECIALIZER-CLASS (EQL-SPECIALIZER))|
            WALKER::WITH-AUGMENTED-ENVIRONMENT-INTERNAL
            PCL::ONE-CLASS-DFUN-INFO
            PCL::|(FAST-METHOD ACCESSOR-METHOD-CLASS (STANDARD-ACCESSOR-METHOD))|
            PCL::|(FAST-METHOD ACCESSOR-METHOD-CLASS (STANDARD-WRITER-METHOD))|
            PCL::|(FAST-METHOD GENERIC-FUNCTION-PRETTY-ARGLIST
    (STANDARD-GENERIC-FUNCTION))| ITERATE::OPTIMIZE-ITERATE-FORM
            PCL::|(FAST-METHOD COMPUTE-CLASS-PRECEDENCE-LIST (SLOT-CLASS))|
            PCL::MAKE-DFUN-CALL
            PCL::|(FAST-METHOD WRAPPER-FETCHER (STANDARD-CLASS))|
            PCL::|(FAST-METHOD SLOTS-FETCHER (STANDARD-CLASS))|
            PCL::|(FAST-METHOD RAW-INSTANCE-ALLOCATOR (STANDARD-CLASS))|
            PCL::COMPUTE-PRECEDENCE PCL::FIRST-FORM-TO-LISP
            ITERATE::OPTIMIZE-GATHERING-FORM WALKER::RECONS
            ITERATE::SIMPLE-EXPAND-GATHERING-FORM
            ITERATE::RENAME-AND-CAPTURE-VARIABLES
            PCL::MAKE-TOP-LEVEL-FORM WALKER::RELIST-INTERNAL
            ITERATE::VARIABLE-SAME-P PCL::ENTRY-IN-CACHE-P
            PCL::MAKE-OPTIMIZED-STD-SLOT-VALUE-USING-CLASS-METHOD-FUNCTION
            PCL::MAKE-OPTIMIZED-STD-SETF-SLOT-VALUE-USING-CLASS-METHOD-FUNCTION
            PCL::MAKE-OPTIMIZED-STD-SLOT-BOUNDP-USING-CLASS-METHOD-FUNCTION
            PCL::|(FAST-METHOD INITIALIZE-INTERNAL-SLOT-FUNCTIONS
    (EFFECTIVE-SLOT-DEFINITION))|
            PCL::WRAP-METHOD-GROUP-SPECIFIER-BINDINGS
            PCL::|(FAST-METHOD SLOT-DEFINITION-ALLOCATION (STRUCTURE-SLOT-DEFINITION))|
            PCL::MAP-ALL-ORDERS
            PCL::|(FAST-METHOD CLASS-FINALIZED-P (PCL-CLASS))|
            PCL::|(FAST-METHOD CLASS-DIRECT-DEFAULT-INITARGS (SLOT-CLASS))|
            PCL::|(FAST-METHOD CLASS-DEFAULT-INITARGS (SLOT-CLASS))|
            PCL::|(FAST-METHOD CLASS-CONSTRUCTORS (SLOT-CLASS))|
            PCL::|(FAST-METHOD CLASS-SLOT-CELLS (STD-CLASS))|
            PCL::CAN-OPTIMIZE-ACCESS PCL::OPTIMIZE-SLOT-VALUE
            PCL::OPTIMIZE-SET-SLOT-VALUE PCL::OPTIMIZE-SLOT-BOUNDP
            SYSTEM::APPLY-DISPLAY-FUN
            PCL::|(FAST-METHOD UPDATE-CONSTRUCTORS (SLOT-CLASS))|
            PCL::|(FAST-METHOD UPDATE-CONSTRUCTORS (CLASS))|
            PCL::TRACE-EMF-CALL-INTERNAL
            PCL::|(FAST-METHOD MAKE-INSTANCES-OBSOLETE (STD-CLASS))|
            PCL::GET-FUNCTION-GENERATOR
            PCL::|(FAST-METHOD SPECIALIZER-DIRECT-METHODS (CLASS))|
            WALKER:VARIABLE-DECLARATION PCL::COMPUTE-STD-CPL-PHASE-3
            PCL::|(FAST-METHOD SPECIALIZER-DIRECT-GENERIC-FUNCTIONS (CLASS))|)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T) T) WALKER::WALK-LET/LET*
            WALKER::WALK-PROG/PROG*
            PCL::|(FAST-METHOD CHANGE-CLASS (STANDARD-OBJECT STANDARD-CLASS))|
            WALKER::WALK-DO/DO* WALKER::WALK-BINDINGS-2
            PCL::|(FAST-METHOD CHANGE-CLASS (STANDARD-OBJECT FUNCALLABLE-STANDARD-CLASS))|
            PCL::|(FAST-METHOD ADD-DIRECT-METHOD (SPECIALIZER-WITH-OBJECT METHOD))|
            PCL::|(FAST-METHOD REMOVE-DIRECT-METHOD (SPECIALIZER-WITH-OBJECT METHOD))|
            PCL::OPTIMIZE-READER PCL::OPTIMIZE-WRITER
            PCL::|(FAST-METHOD VALIDATE-SUPERCLASS (CLASS BUILT-IN-CLASS))|
            PCL::|(FAST-METHOD VALIDATE-SUPERCLASS (SLOT-CLASS FORWARD-REFERENCED-CLASS))|
            PCL::FILL-CACHE-P
            PCL::|(FAST-METHOD ADD-DEPENDENT (DEPENDENT-UPDATE-MIXIN T))|
            PCL::ADJUST-CACHE PCL::EXPAND-CACHE
            PCL::|(FAST-METHOD REMOVE-DEPENDENT (DEPENDENT-UPDATE-MIXIN T))|
            PCL::|(FAST-METHOD REINITIALIZE-INSTANCE :BEFORE (SLOT-CLASS))|
            PCL::|(FAST-METHOD MAP-DEPENDENTS (DEPENDENT-UPDATE-MIXIN T))|
            PCL::|(FAST-METHOD DIRECT-SLOT-DEFINITION-CLASS (STRUCTURE-CLASS T))|
            PCL::|(FAST-METHOD PRINT-OBJECT (STANDARD-METHOD-COMBINATION T))|
            PCL::|(FAST-METHOD DIRECT-SLOT-DEFINITION-CLASS (STD-CLASS T))|
            PCL::|(FAST-METHOD VALIDATE-SUPERCLASS
    (FUNCALLABLE-STANDARD-CLASS STANDARD-CLASS))|
            PCL::|(FAST-METHOD LEGAL-DOCUMENTATION-P (STANDARD-METHOD T))|
            PCL::INITIALIZE-INSTANCE-SIMPLE
            PCL::|(FAST-METHOD LEGAL-LAMBDA-LIST-P (STANDARD-METHOD T))|
            PCL::|(FAST-METHOD LEGAL-METHOD-FUNCTION-P (STANDARD-METHOD T))|
            PCL::|(FAST-METHOD LEGAL-QUALIFIER-P (STANDARD-METHOD T))|
            PCL::|(FAST-METHOD LEGAL-SLOT-NAME-P (STANDARD-METHOD T))|
            PCL::|(FAST-METHOD ALLOCATE-INSTANCE (FUNCALLABLE-STANDARD-CLASS))|
            PCL::MAYBE-EXPAND-ACCESSOR-FORM
            PCL::|(FAST-METHOD LEGAL-SPECIALIZER-P (STANDARD-METHOD T))|
            PCL::|(FAST-METHOD PRINT-OBJECT (GENERIC-FUNCTION T))|
            PCL::|(FAST-METHOD MAKE-READER-METHOD-FUNCTION
    (FUNCALLABLE-STANDARD-CLASS T))|
            PCL::LOAD-PRECOMPILED-DFUN-CONSTRUCTOR PCL::GET-CACHE
            PCL::|(FAST-METHOD MAKE-WRITER-METHOD-FUNCTION
    (FUNCALLABLE-STANDARD-CLASS T))|
            PCL::|(FAST-METHOD INITIALIZE-INSTANCE :AFTER (STANDARD-GENERIC-FUNCTION))|
            PCL::|(FAST-METHOD REINITIALIZE-INSTANCE :AFTER (STANDARD-GENERIC-FUNCTION))|
            PCL::|(FAST-METHOD COMPUTE-APPLICABLE-METHODS (GENERIC-FUNCTION T))|
            PCL::|(FAST-METHOD SAME-SPECIALIZER-P (SPECIALIZER SPECIALIZER))|
            PCL::GET-WRAPPERS-FROM-CLASSES
            PCL::|(FAST-METHOD SAME-SPECIALIZER-P (CLASS CLASS))|
            PCL::|(FAST-METHOD SAME-SPECIALIZER-P
    (CLASS-EQ-SPECIALIZER CLASS-EQ-SPECIALIZER))|
            PCL::|(FAST-METHOD PRINT-OBJECT (T T))|
            PCL::|(FAST-METHOD SAME-SPECIALIZER-P (EQL-SPECIALIZER EQL-SPECIALIZER))|
            PCL::|(FAST-METHOD PRINT-OBJECT (CLASS T))|
            PCL::|(FAST-METHOD PRINT-OBJECT (SLOT-DEFINITION T))|
            PCL::|(FAST-METHOD INFORM-TYPE-SYSTEM-ABOUT-CLASS (STRUCTURE-CLASS T))|
            PCL::TWO-CLASS-DFUN-INFO PCL::SET-MAKE-INSTANCE-FUNCTION
            PCL::|(FAST-METHOD UPDATE-GF-DFUN (STD-CLASS T))|
            PCL::|(FAST-METHOD PRINT-OBJECT (STANDARD-METHOD T))|
            PCL::|(FAST-METHOD PRINT-OBJECT (STANDARD-ACCESSOR-METHOD T))|
            PCL::|(FAST-METHOD REINITIALIZE-INSTANCE (STANDARD-METHOD))|
            WALKER::WALK-TEMPLATE PCL::EXPAND-DEFCLASS
            PCL::BOOTSTRAP-SET-SLOT
            PCL::|(FAST-METHOD ALLOCATE-INSTANCE (STANDARD-CLASS))|
            PCL::|(FAST-METHOD SLOT-ACCESSOR-STD-P (EFFECTIVE-SLOT-DEFINITION T))|
            PCL::|(FAST-METHOD DOCUMENTATION (T))|
            PCL::|(FAST-METHOD DOCUMENTATION (DOCUMENTATION-MIXIN))|
            PCL::|(FAST-METHOD EFFECTIVE-SLOT-DEFINITION-CLASS (STD-CLASS T))|
            PCL::|(FAST-METHOD EFFECTIVE-SLOT-DEFINITION-CLASS (STRUCTURE-CLASS T))|
            PCL::|(FAST-METHOD COMPUTE-EFFECTIVE-SLOT-DEFINITION-INITARGS (SLOT-CLASS T))|
            PCL::|(FAST-METHOD COMPUTE-EFFECTIVE-SLOT-DEFINITION-INITARGS :AROUND
    (STRUCTURE-CLASS T))| PCL::MAKE-EFFECTIVE-METHOD-FUNCTION1
            PCL::MAKE-EFFECTIVE-METHOD-FUNCTION-INTERNAL
            PCL::MAKE-EFFECTIVE-METHOD-FUNCTION-TYPE
            PCL::|(FAST-METHOD REMOVE-READER-METHOD (SLOT-CLASS T))|
            PCL::|(FAST-METHOD REMOVE-WRITER-METHOD (SLOT-CLASS T))|
            PCL::EMIT-CHECKING-OR-CACHING-FUNCTION-PRELIMINARY
            PCL::MEMF-TEST-CONVERTER
            PCL::|(FAST-METHOD REMOVE-BOUNDP-METHOD (SLOT-CLASS T))|
            PCL::|(FAST-METHOD MAKE-READER-METHOD-FUNCTION (SLOT-CLASS T))|
            PCL::|(FAST-METHOD ADD-DIRECT-SUBCLASS (CLASS CLASS))|
            PCL::|(FAST-METHOD MAKE-WRITER-METHOD-FUNCTION (SLOT-CLASS T))|
            PCL::|(FAST-METHOD MAKE-INSTANCE (CLASS))|
            PCL::|(FAST-METHOD REMOVE-DIRECT-SUBCLASS (CLASS CLASS))|
            PCL::EXPAND-SYMBOL-MACROLET-INTERNAL
            PCL::|(FAST-METHOD MAKE-BOUNDP-METHOD-FUNCTION (SLOT-CLASS T))|
            PCL::|(FAST-METHOD INFORM-TYPE-SYSTEM-ABOUT-CLASS (STD-CLASS T))|
            PCL::|(FAST-METHOD ADD-DIRECT-METHOD (CLASS METHOD))|
            PCL::|(FAST-METHOD REINITIALIZE-INSTANCE (SLOT-OBJECT))|
            PCL::|(FAST-METHOD REMOVE-DIRECT-METHOD (CLASS METHOD))|
            PCL::|(FAST-METHOD COMPATIBLE-META-CLASS-CHANGE-P (T T))|
            PCL::|(FAST-METHOD VALIDATE-SUPERCLASS (CLASS CLASS))|)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T) T)
            PCL::REAL-MAKE-METHOD-INITARGS-FORM PCL::MAKE-FGEN
            WALKER::WALK-BINDINGS-1
            PCL::|(FAST-METHOD SHARED-INITIALIZE :BEFORE (BUILT-IN-CLASS T))|
            PCL::COMPUTE-PV-SLOT
            PCL::|(FAST-METHOD ENSURE-CLASS-USING-CLASS (T NULL))|
            PCL::|(FAST-METHOD ENSURE-CLASS-USING-CLASS (T PCL-CLASS))|
            PCL::OPTIMIZE-INSTANCE-ACCESS
            PCL::BOOTSTRAP-MAKE-SLOT-DEFINITIONS
            PCL::OPTIMIZE-ACCESSOR-CALL
            PCL::BOOTSTRAP-ACCESSOR-DEFINITIONS
            PCL::|(FAST-METHOD SHARED-INITIALIZE :AFTER (STD-CLASS T))|
            PCL::|(FAST-METHOD SHARED-INITIALIZE :AFTER (STRUCTURE-CLASS T))|
            PCL::|(FAST-METHOD COMPUTE-EFFECTIVE-METHOD
    (GENERIC-FUNCTION STANDARD-METHOD-COMBINATION T))|
            PCL::MAKE-PARAMETER-REFERENCES PCL::UPDATE-SLOTS-IN-PV
            PCL::|(FAST-METHOD SHARED-INITIALIZE :BEFORE (STANDARD-ACCESSOR-METHOD T))|
            PCL::|(FAST-METHOD SHARED-INITIALIZE :AFTER (STANDARD-METHOD T))|
            PCL::|(FAST-METHOD REMOVE-NAMED-METHOD (T T))|
            PCL::|(FAST-METHOD SHARED-INITIALIZE :AFTER (STRUCTURE-SLOT-DEFINITION T))|
            PCL::MAKE-EMF-CACHE PCL::MAKE-INSTANCE-FUNCTION-COMPLEX
            PCL::MAKE-INSTANCE-FUNCTION-SIMPLE
            WALKER::WALK-TEMPLATE-HANDLE-REPEAT
            PCL::|(FAST-METHOD SLOT-BOUNDP-USING-CLASS
    (STD-CLASS STANDARD-OBJECT STANDARD-EFFECTIVE-SLOT-DEFINITION))|
            PCL::|(FAST-METHOD SLOT-MAKUNBOUND-USING-CLASS
    (STD-CLASS STANDARD-OBJECT STANDARD-EFFECTIVE-SLOT-DEFINITION))|
            PCL::|(FAST-METHOD SLOT-BOUNDP-USING-CLASS
    (STRUCTURE-CLASS STRUCTURE-OBJECT
        STRUCTURE-EFFECTIVE-SLOT-DEFINITION))|
            PCL::|(FAST-METHOD SLOT-MAKUNBOUND-USING-CLASS
    (STRUCTURE-CLASS STRUCTURE-OBJECT
        STRUCTURE-EFFECTIVE-SLOT-DEFINITION))|
            PCL::|(FAST-METHOD SLOT-UNBOUND (T T T))|
            PCL::|(FAST-METHOD (SETF SLOT-ACCESSOR-STD-P)
    (T EFFECTIVE-SLOT-DEFINITION T))|
            PCL::|(FAST-METHOD COMPUTE-SLOT-ACCESSOR-INFO
    (EFFECTIVE-SLOT-DEFINITION T T))|
            PCL::|(FAST-METHOD SHARED-INITIALIZE :AFTER (DOCUMENTATION-MIXIN T))|
            PCL::|(FAST-METHOD FIND-METHOD-COMBINATION
    (GENERIC-FUNCTION (EQL STANDARD) T))|
            PCL::|(FAST-METHOD (SETF DOCUMENTATION) (T T))|
            PCL::|(FAST-METHOD COMPUTE-EFFECTIVE-METHOD
    (GENERIC-FUNCTION SHORT-METHOD-COMBINATION T))|
            PCL::|(FAST-METHOD (SETF DOCUMENTATION) (T DOCUMENTATION-MIXIN))|
            PCL::|(FAST-METHOD READER-METHOD-CLASS (SLOT-CLASS T))|
            PCL::|(FAST-METHOD WRITER-METHOD-CLASS (SLOT-CLASS T))|
            PCL::EXPAND-EMF-CALL-METHOD
            PCL::OPTIMIZE-GENERIC-FUNCTION-CALL
            PCL::MAKE-FINAL-ORDINARY-DFUN-INTERNAL
            PCL::LOAD-FUNCTION-GENERATOR)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T *) T) PCL::MAKE-DEFMETHOD-FORM
            PCL::MAKE-DEFMETHOD-FORM-INTERNAL PCL::LOAD-DEFMETHOD
            PCL::EARLY-MAKE-A-METHOD PCL::SET-ARG-INFO)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T *) T) PCL::FILL-DFUN-CACHE
            PCL::EARLY-ADD-NAMED-METHOD PCL::REAL-ADD-NAMED-METHOD)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T *) T) WALKER::WALK-ARGLIST
            PCL::CAN-OPTIMIZE-ACCESS1 PCL::EMIT-FETCH-WRAPPER
            PCL::CHECK-INITARGS-1 PCL::MAKE-EMF-CALL PCL::FILL-CACHE
            PCL::CHECK-INITARGS-2-PLIST PCL::REAL-GET-METHOD
            PCL::CHECK-INITARGS-2-LIST PCL::GET-METHOD)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T T) T) PCL::EXPAND-DEFMETHOD
            PCL::LOAD-DEFMETHOD-INTERNAL
            PCL::|(FAST-METHOD SLOT-MISSING (T T T T))|)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T) T)
            PCL::BOOTSTRAP-MAKE-SLOT-DEFINITION PCL::EMIT-SLOT-ACCESS
            PCL::OPTIMIZE-GF-CALL PCL::LOAD-DEFCLASS
            WALKER::WALK-TEMPLATE-HANDLE-REPEAT-1
            PCL::MAKE-EARLY-CLASS-DEFINITION
            PCL::|(FAST-METHOD (SETF SLOT-VALUE-USING-CLASS)
    (T STD-CLASS STANDARD-OBJECT STANDARD-EFFECTIVE-SLOT-DEFINITION))|)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T T T) T)
            PCL::GET-SECONDARY-DISPATCH-FUNCTION2)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T *) T) PCL::EMIT-DLAP
            PCL::GET-MAKE-INSTANCE-FUNCTION-INTERNAL
            PCL::GET-SECONDARY-DISPATCH-FUNCTION1)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T FIXNUM) T) PCL::FILL-CACHE-FROM-CACHE-P)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T T T T *) T)
            PCL::BOOTSTRAP-INITIALIZE-CLASS)) 
(PROCLAIM
    '(FTYPE (FUNCTION NIL *) PCL::COUNT-ALL-DFUNS PCL::EMIT-N-N-READERS
            PCL::EMIT-N-N-WRITERS PCL::RENEW-SYS-FILES)) 
(PROCLAIM
    '(FTYPE (FUNCTION NIL T)
            PCL::INITIALIZE-CHECKING-OR-CACHING-FUNCTION-LIST
            PCL::SHOW-EMF-CALL-TRACE PCL::MAKE-CACHE PCL::MAKE-CPD
            PCL::BOOTSTRAP-META-BRAID PCL::EARLY-INITIALIZE-SLOT-GFS
            PCL::EARLY-INITIALIZE-CLASS-PREDICATES
            PCL::BOOTSTRAP-BUILT-IN-CLASSES PCL::UPDATE-DISPATCH-DFUNS
            PCL::SHOW-FREE-CACHE-VECTORS PCL::NO-METHODS-DFUN-INFO
            PCL::IN-THE-COMPILER-P PCL::STRUCTURE-FUNCTIONS-EXIST-P
            PCL::%%ALLOCATE-INSTANCE--CLASS
            PCL::ALLOCATE-FUNCALLABLE-INSTANCE-2
            PCL::ALLOCATE-FUNCALLABLE-INSTANCE-1
            PCL::DEFAULT-METHOD-ONLY-DFUN-INFO
            PCL::INITIAL-DISPATCH-DFUN-INFO PCL::INITIAL-DFUN-INFO
            PCL::MAKE-ARG-INFO PCL::DISPATCH-DFUN-INFO
            PCL::SHOW-DFUN-CONSTRUCTORS PCL::CACHES-TO-ALLOCATE
            PCL::RESET-PCL-PACKAGE PCL::GET-EFFECTIVE-METHOD-GENSYM
            PCL::LIST-ALL-DFUNS)) 
(PROCLAIM
    '(FTYPE (FUNCTION (*) *) PCL::LIST-LARGE-CACHES
            PCL:INVALID-METHOD-ERROR PCL:METHOD-COMBINATION-ERROR
            PCL::UNTRACE-METHOD)) 
(PROCLAIM '(FTYPE (FUNCTION (FIXNUM T *) *) PCL::FIND-FREE-CACHE-LINE)) 
(PROCLAIM
    '(FTYPE (FUNCTION (FIXNUM T T) *) PCL::COMPUTE-CACHE-PARAMETERS)) 
(PROCLAIM
    '(FTYPE (FUNCTION (*) T) PCL::MAKE-METHOD-CALL
            PCL::MAKE-FAST-METHOD-CALL PCL::MAKE-FAST-INSTANCE-BOUNDP
            PCL::PV-WRAPPERS-FROM-PV-ARGS PCL::MAKE-PV-TABLE
            PCL::|__si::MAKE-ARG-INFO| PCL::|__si::MAKE-PV-TABLE|
            PCL::FIX-EARLY-GENERIC-FUNCTIONS PCL::|__si::MAKE-CACHE|
            PCL::|__si::MAKE-NO-METHODS| PCL::|__si::MAKE-STD-INSTANCE|
            PCL::CALLED-FIN-WITHOUT-FUNCTION
            WALKER::UNBOUND-LEXICAL-FUNCTION PCL::MAKE-INITIALIZE-INFO
            PCL::UPDATE-MAKE-INSTANCE-FUNCTION-TABLE
            PCL::|__si::MAKE-DFUN-INFO|
            PCL::|__si::MAKE-DEFAULT-METHOD-ONLY|
            PCL::|__si::MAKE-ACCESSOR-DFUN-INFO| PCL::MAKE-PROGN
            PCL::|__si::MAKE-ONE-INDEX-DFUN-INFO| PCL::|__si::MAKE-N-N|
            PCL::|__si::MAKE-CLASS-PRECEDENCE-DESCRIPTION|
            PCL::|__si::MAKE-ONE-CLASS| PCL::|__si::MAKE-TWO-CLASS|
            PCL::|__si::MAKE-ONE-INDEX| PCL::|__si::MAKE-CHECKING|
            PCL::|__si::MAKE-CACHING| PCL::|__si::MAKE-CONSTANT-VALUE|
            PCL::INTERN-PV-TABLE PCL::TRUE PCL::|__si::MAKE-DISPATCH|
            PCL::STRING-APPEND PCL::|__si::MAKE-INITIAL| PCL::FALSE
            PCL::|__si::MAKE-INITIAL-DISPATCH|
            PCL::|STRUCTURE-OBJECT class constructor|)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) *) PCL::METHOD-PROTOTYPE-FOR-GF
            PCL::FIND-WRAPPER PCL::PARSE-DEFMETHOD
            PCL::PROTOTYPES-FOR-MAKE-METHOD-LAMBDA
            PCL::FORCE-CACHE-FLUSHES PCL::STRUCTURE-WRAPPER
            PCL::EMIT-ONE-CLASS-READER PCL::EMIT-ONE-CLASS-WRITER
            PCL::EMIT-TWO-CLASS-READER PCL::EMIT-TWO-CLASS-WRITER
            PCL::EMIT-ONE-INDEX-READERS PCL::EMIT-ONE-INDEX-WRITERS
            PCL::EARLY-METHOD-FUNCTION PCL::EMIT-IN-CHECKING-CACHE-P
            PCL::EMIT-CONSTANT-VALUE
            PCL::COMPUTE-APPLICABLE-METHODS-EMF PCL::NET-CODE-CONVERTER
            PCL::STRUCTURE-SLOTD-INIT-FORM PCL::MAKE-DISPATCH-DFUN
            PCL::INSURE-CACHING-DFUN PCL::%FBOUNDP PCL::CCLOSUREP
            PCL::EARLY-COLLECT-INHERITANCE PCL::TYPE-FROM-SPECIALIZER
            PCL::*NORMALIZE-TYPE PCL::UNPARSE-TYPE
            PCL::CONVERT-TO-SYSTEM-TYPE PCL::PCL-DESCRIBE
            PCL::PARSE-METHOD-GROUP-SPECIFIER PCL::ANALYZE-LAMBDA-LIST
            COMPILER::CAN-USE-PRINT-CIRCLE-P PCL::GF-LAMBDA-LIST
            PCL::SPECIALIZER-FROM-TYPE PCL::CLASS-EQ-TYPE
            PCL::FIND-STRUCTURE-CLASS PCL::GENERIC-FUNCTION-NAME-P
            PCL::GET-DISPATCH-FUNCTION PCL::DEFAULT-CODE-CONVERTER
            PCL::MAKE-FINAL-DISPATCH-DFUN)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) T) PCL::FGEN-GENERATOR PCL::FGEN-SYSTEM
            PCL::STORE-FGEN PCL::MAKE-PV-TYPE-DECLARATION
            PCL::MAKE-CALLS-TYPE-DECLARATION PCL::CHECK-CACHE
            PCL::FGEN-GENSYMS PCL::MAKE-CONSTANT-FUNCTION
            PCL::FGEN-GENERATOR-LAMBDA PCL::FUNCTION-RETURNING-T
            PCL::METHOD-CALL-P PCL::FIND-CYCLE-REASONS
            PCL::MAP-ALL-GENERIC-FUNCTIONS PCL::MAKE-PERMUTATION-VECTOR
            PCL::FAST-METHOD-CALL-P PCL::ALLOCATE-CACHE-VECTOR
            PCL::FLUSH-CACHE-VECTOR-INTERNAL PCL::FORMAT-CYCLE-REASONS
            PCL::FAST-INSTANCE-BOUNDP-P PCL::METHOD-FUNCTION-PV-TABLE
            PCL::METHOD-FUNCTION-METHOD
            PCL::DO-STANDARD-DEFSETFS-FOR-DEFCLASS
            PCL::GET-CACHE-VECTOR
            PCL::METHOD-FUNCTION-NEEDS-NEXT-METHODS-P
            PCL::WRAPPER-FIELD PCL::FREE-CACHE-VECTOR
            PCL::METHOD-FUNCTION-PLIST PCL::SORT-SLOTS
            PCL::MAP-SPECIALIZERS
            PCL::FTYPE-DECLARATION-FROM-LAMBDA-LIST
            PCL::ONE-INDEX-DFUN-INFO-CACHE PCL::SORT-CALLS
            PCL::ONE-INDEX-DFUN-INFO-ACCESSOR-TYPE PCL::DFUN-ARG-SYMBOL
            PCL::N-N-CACHE PCL::GF-DFUN-CACHE PCL::N-N-ACCESSOR-TYPE
            PCL::GDEFINITION PCL::GF-DFUN-INFO PCL::ONE-CLASS-CACHE
            PCL::EVAL-FORM PCL::EARLY-GF-NAME
            PCL::ONE-CLASS-ACCESSOR-TYPE
            PCL::SLOT-INITARGS-FROM-STRUCTURE-SLOTD
            PCL::ONE-CLASS-INDEX
            PCL:EXTRACT-LAMBDA-LIST PCL::SYMBOL-PKG-NAME
            PCL::TWO-CLASS-CACHE PCL:EXTRACT-SPECIALIZER-NAMES
            PCL::ARG-INFO-PRECEDENCE PCL::TWO-CLASS-ACCESSOR-TYPE
            PCL::ARG-INFO-METATYPES PCL::TWO-CLASS-INDEX
            PCL::INITIALIZE-INFO-KEY PCL::INTERNED-SYMBOL-P
            PCL::ARG-INFO-NUMBER-OPTIONAL PCL::TWO-CLASS-WRAPPER0
            PCL::INITIALIZE-INFO-WRAPPER PCL::FREE-CACHE
            PCL::CLASS-HAS-A-FORWARD-REFERENCED-SUPERCLASS-P
            PCL::ARG-INFO-KEY/REST-P PCL::ONE-INDEX-CACHE
            PCL::ARG-INFO-KEYWORDS PCL::ONE-INDEX-ACCESSOR-TYPE
            PCL::GF-INFO-SIMPLE-ACCESSOR-TYPE PCL::ONE-INDEX-INDEX
            PCL::UPDATE-GFS-OF-CLASS PCL::GF-PRECOMPUTE-DFUN-AND-EMF-P
            PCL::CHECKING-CACHE PCL::GF-INFO-STATIC-C-A-M-EMF
            PCL::CACHING-CACHE PCL::GF-INFO-C-A-M-EMF-STD-P
            PCL::CONSTANT-VALUE-CACHE PCL::UPDATE-CLASS-CAN-PRECEDE-P
            PCL::GF-INFO-FAST-MF-P PCL::COMPUTE-CLASS-SLOTS
            PCL::ARG-INFO-LAMBDA-LIST PCL:INTERN-EQL-SPECIALIZER
            PCL::ARG-INFO-P PCL::ARG-INFO-VALID-P PCL::ARG-INFO-NKEYS
            PCL::COMPILE-IIS-FUNCTIONS PCL::ARG-INFO-APPLYP
            PCL::WRAPPER-FOR-STRUCTURE PCL::PV-TABLEP
            PCL::UPDATE-GF-INFO PCL::MAKE-PV-TABLE-TYPE-DECLARATION
            PCL::BUILT-IN-WRAPPER-OF PCL::CACHE-P
            PCL::BUILT-IN-OR-STRUCTURE-WRAPPER1
            PCL::RESET-INITIALIZE-INFO PCL::UPDATE-PV-TABLE-CACHE-INFO
            PCL::UPDATE-C-A-M-GF-INFO
            PCL::UPDATE-GF-SIMPLE-ACCESSOR-TYPE
            PCL::INITIALIZE-INFO-CACHED-VALID-P PCL::EARLY-CLASS-NAME
            PCL::NO-METHODS-P PCL::STANDARD-SVUC-METHOD
            PCL::INTERN-FUNCTION-NAME
            PCL::INITIALIZE-INFO-CACHED-RI-VALID-P
            PCL::STRUCTURE-SVUC-METHOD PCL::COMPILE-LAMBDA-UNCOMPILED
            PCL::INITIALIZE-INFO-CACHED-INITARGS-FORM-LIST
            PCL::COMPILE-LAMBDA-DEFERRED
            PCL::INITIALIZE-INFO-CACHED-NEW-KEYS
            PCL::INITIALIZE-INFO-CACHED-DEFAULT-INITARGS-FUNCTION
            PCL::UNDEFMETHOD-1
            PCL::INITIALIZE-INFO-CACHED-SHARED-INITIALIZE-T-FUNCTION
            PCL::METHOD-LL->GENERIC-FUNCTION-LL
            PCL::COMPUTE-MCASE-PARAMETERS
            PCL::INITIALIZE-INFO-CACHED-SHARED-INITIALIZE-NIL-FUNCTION
            PCL::INITIALIZE-INFO-CACHED-CONSTANTS PCL::COPY-CACHE
            PCL::NET-TEST-CONVERTER
            PCL::INITIALIZE-INFO-CACHED-COMBINED-INITIALIZE-FUNCTION
            PCL::COMPUTE-LINE-SIZE
            PCL::ACCESSOR-DFUN-INFO-ACCESSOR-TYPE
            PCL::UPDATE-ALL-C-A-M-GF-INFO
            PCL::ONE-INDEX-DFUN-INFO-INDEX PCL::ONE-CLASS-WRAPPER0
            PCL::EXTRACT-PARAMETERS PCL::TWO-CLASS-WRAPPER1
            PCL::EXTRACT-REQUIRED-PARAMETERS
            PCL::FUNCTION-PRETTY-ARGLIST PCL::CHECKING-FUNCTION
            PCL::CLASS-FROM-TYPE PCL::DNET-METHODS-P
            PCL::PROCLAIM-INCOMPATIBLE-SUPERCLASSES
            PCL::FUNCALLABLE-INSTANCE-P PCL::DEFAULT-STRUCTUREP
            PCL::DEFAULT-STRUCTURE-INSTANCE-P PCL::GFS-OF-TYPE
            PCL::DEFAULT-STRUCTURE-TYPE PCL::STRUCTURE-TYPE
            PCL::STRUCTURE-TYPE-INCLUDED-TYPE-NAME
            PCL::RESET-CLASS-INITIALIZE-INFO
            PCL::STRUCTURE-TYPE-SLOT-DESCRIPTION-LIST
            PCL::CONSTANT-SYMBOL-P PCL::STRUCTURE-SLOTD-NAME
            PCL::MAKE-INSTANCE-FUNCTION-SYMBOL
            PCL::STRUCTURE-SLOTD-ACCESSOR-SYMBOL
            PCL::MAKE-LAZY-GET-MAKE-INSTANCE-FUNCTION
            PCL::%STD-INSTANCE-WRAPPER
            PCL::STRUCTURE-SLOTD-WRITER-FUNCTION
            PCL::%STD-INSTANCE-SLOTS PCL::STRUCTURE-SLOTD-TYPE
            PCL::STD-INSTANCE-P PCL::CONSTANT-VALUE-P
            PCL::USE-CACHING-DFUN-P
            PCL::COMPLICATED-INSTANCE-CREATION-METHOD
            PCL::MAKE-FUNCTION-INLINE
            PCL::SLOT-VECTOR-SYMBOL PCL::CACHING-DFUN-INFO
            PCL::COMPUTE-APPLICABLE-METHODS-EMF-STD-P
            PCL::CONSTANT-VALUE-DFUN-INFO
            PCL::STRUCTURE-TYPE-INTERNAL-SLOTDS WALKER::ENV-LOCK
            PCL::CPD-CLASS WALKER::ENV-LEXICAL-VARIABLES
            PCL::RESET-CLASS-INITIALIZE-INFO-1 WALKER::ENV-DECLARATIONS
            ITERATE::VARIABLES-FROM-LET
            WALKER::GET-IMPLEMENTATION-DEPENDENT-WALKER-TEMPLATE
            PCL::UPDATE-INITIALIZE-INFO PCL::CPD-SUPERS
            WALKER::ENV-WALK-FORM WALKER::ENV-WALK-FUNCTION
            PCL::DEFAULT-SECONDARY-DISPATCH-FUNCTION PCL::CPD-AFTER
            PCL::EARLY-CLASS-DEFINITION WALKER::GET-WALKER-TEMPLATE
            PCL::GET-PV-CELL-FOR-CLASS ITERATE::SEQUENCE-ACCESSOR
            PCL::CPD-COUNT PCL::%SYMBOL-FUNCTION PCL::%CCLOSURE-ENV
            PCL::EARLY-CLASS-PRECEDENCE-LIST
            PCL::INFORM-TYPE-SYSTEM-ABOUT-STD-CLASS
            PCL::MAKE-INITFUNCTION PCL::DFUN-INFO-P PCL::ECD-CLASS-NAME
            PCL::DISPATCH-P PCL::CANONICAL-SLOT-NAME
            PCL::EARLY-CLASS-SLOTS PCL::EARLY-COLLECT-CPL
            PCL::EARLY-COLLECT-SLOTS PCL::DEFAULT-METHOD-ONLY-P
            PCL::METHODS-CONTAIN-EQL-SPECIALIZER-P
            PCL::EARLY-COLLECT-DEFAULT-INITARGS
            PCL::ECD-SUPERCLASS-NAMES PCL::ECD-CANONICAL-SLOTS
            PCL::UNENCAPSULATED-FDEFINITION PCL::ECD-OTHER-INITARGS
            PCL::FAST-METHOD-CALL-ARG-INFO PCL::MAKE-INITIAL-DFUN
            PCL::ACCESSOR-DFUN-INFO-P PCL::ECD-SOURCE
            PCL::ECD-METACLASS PCL::MAKE-TYPE-PREDICATE
            PCL::ONE-INDEX-DFUN-INFO-P PCL::EARLY-CLASS-NAME-OF
            PCL::UNPARSE-TYPE-LIST PCL::EARLY-CLASS-DIRECT-SUBCLASSES
            PCL::N-N-P PCL::SLOT-READER-SYMBOL PCL::SLOT-WRITER-SYMBOL
            PCL::SLOT-BOUNDP-SYMBOL
            PCL::MAKE-STRUCTURE-SLOT-BOUNDP-FUNCTION PCL::ONE-CLASS-P
            PCL::MAKE-OPTIMIZED-STRUCTURE-SLOT-VALUE-USING-CLASS-METHOD-FUNCTION
            PCL::GBOUNDP
            PCL::MAKE-OPTIMIZED-STRUCTURE-SETF-SLOT-VALUE-USING-CLASS-METHOD-FUNCTION
            PCL::GMAKUNBOUND
            PCL::MAKE-OPTIMIZED-STRUCTURE-SLOT-BOUNDP-USING-CLASS-METHOD-FUNCTION
            PCL::CLASS-PRECEDENCE-DESCRIPTION-P PCL::TWO-CLASS-P
            PCL::EXPAND-LONG-DEFCOMBIN PCL::STRUCTURE-SLOT-BOUNDP
            PCL::ONE-INDEX-P PCL::CHECKING-P
            PCL::MAKE-DEFAULT-METHOD-GROUP-DESCRIPTION
            SYSTEM:%STRUCTURE-NAME PCL::INITIALIZE-INTERNAL-SLOT-GFS
            SYSTEM:%COMPILED-FUNCTION-NAME PCL::CACHING-P
            PCL::EXPAND-SHORT-DEFCOMBIN
            PCL::USE-DEFAULT-METHOD-ONLY-DFUN-P
            PCL::METHOD-FUNCTION-FROM-FAST-FUNCTION
            PCL::KEYWORD-SPEC-NAME PCL:CLASS-OF
            PCL::GENERIC-CLOBBERS-FUNCTION PCL::FUNCTION-RETURNING-NIL
            PCL::EARLY-METHOD-LAMBDA-LIST PCL::DO-STANDARD-DEFSETF-1
            PCL::EARLY-GF-P PCL::PARSE-SPECIALIZERS PCL::TYPE-CLASS
            PCL::MAKE-CALL-METHODS PCL::EARLY-METHOD-QUALIFIERS
            PCL::CLASS-PREDICATE PCL::LEGAL-CLASS-NAME-P
            PCL::MAKE-CLASS-EQ-PREDICATE PCL::STRUCTURE-TYPE-P
            PCL::MAKE-EQL-PREDICATE
            PCL::EARLY-METHOD-STANDARD-ACCESSOR-P
            PCL::NEXT-WRAPPER-FIELD PCL::GET-BUILT-IN-CLASS-SYMBOL
            PCL::GET-BUILT-IN-WRAPPER-SYMBOL PCL::UNPARSE-SPECIALIZERS
            PCL::SETFBOUNDP PCL::GET-SETF-FUNCTION-NAME
            PCL::METHOD-CALL-CALL-METHOD-ARGS SYSTEM::NEXT-STACK-FRAME
            PCL::INITIALIZE-INFO-P PCL::WRAPPER-OF
            PCL::FAST-METHOD-CALL-PV-CELL PCL::CHECK-WRAPPER-VALIDITY
            PCL::FAST-METHOD-CALL-NEXT-METHOD-CALL PCL::INITIAL-P
            PCL::DEFAULT-TEST-CONVERTER PCL::COMPUTE-STD-CPL-PHASE-2
            PCL::DFUN-INFO-CACHE PCL::DEFAULT-CONSTANT-CONVERTER
            WALKER:VARIABLE-GLOBALLY-SPECIAL-P PCL::NO-METHODS-CACHE
            PCL::INITIAL-CACHE PCL::LIST-DFUN
            PCL::INITIAL-DISPATCH-CACHE PCL::STRUCTURE-OBJECT-P
            PCL::LIST-LARGE-CACHE PCL::DEFAULT-CONSTANTP
            PCL::INITIAL-DISPATCH-P PCL::DISPATCH-CACHE PCL::COUNT-DFUN
            PCL::FGEN-TEST PCL::DEFAULT-METHOD-ONLY-CACHE
            PCL::LOOKUP-FGEN PCL::ACCESSOR-DFUN-INFO-CACHE)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T *) *) PCL::GET-FUNCTION PCL::GET-FUNCTION1
            PCL:ENSURE-CLASS PCL::MAKE-METHOD-FUNCTION-INTERNAL
            PCL::PARSE-SPECIALIZED-LAMBDA-LIST
            PCL::MAKE-METHOD-LAMBDA-INTERNAL
            PCL::GET-MAKE-INSTANCE-FUNCTION
            PCL::GET-GENERIC-FUNCTION-INFO PCL::PARSE-METHOD-OR-SPEC
            PCL::COMPILE-LAMBDA PCL::GET-DFUN-CONSTRUCTOR
            PCL::MAKE-CACHING-DFUN PCL::MAKE-CONSTANT-VALUE-DFUN
            PCL::MAKE-FINAL-DFUN-INTERNAL PCL::COERCE-TO-CLASS
            PCL::MAP-ALL-CLASSES PCL:ENSURE-GENERIC-FUNCTION
            PCL::GET-METHOD-FUNCTION PCL::EXTRACT-DECLARATIONS
            WALKER:WALK-FORM WALKER:MACROEXPAND-ALL)) 
(PROCLAIM '(FTYPE (FUNCTION (T T *) (VALUES T T)) PCL::SYMBOL-APPEND)) 
(PROCLAIM '(FTYPE (FUNCTION (T *) STRING) PCL::CAPITALIZE-WORDS)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T) *) PCL::COMPUTE-TEST
            PCL::GET-NEW-FUNCTION-GENERATOR-INTERNAL PCL::COMPUTE-CODE
            PCL::FIND-SUPERCLASS-CHAIN
            PCL::GENERATE-FAST-CLASS-SLOT-ACCESS-P
            PCL::MUTATE-SLOTS-AND-CALLS PCL::ENSURE-CLASS-VALUES
            PCL::MAKE-DIRECT-SLOTD PCL::EMIT-DEFAULT-ONLY-FUNCTION
            PCL::EMIT-DEFAULT-ONLY PCL::SPLIT-DECLARATIONS
            PCL::SLOT-NAME-LISTS-FROM-SLOTS PCL::EMIT-CHECKING
            PCL::EMIT-CACHING PCL::UPDATE-SLOT-VALUE-GF-INFO
            PCL::SET-FUNCTION-NAME PCL::SDFUN-FOR-CACHING
            ITERATE::PARSE-DECLARATIONS
            PCL::COMPUTE-APPLICABLE-METHODS-USING-TYPES
            PCL::INITIALIZE-INSTANCE-SIMPLE-FUNCTION
            PCL::FORM-LIST-TO-LISP PCL::CHECK-INITARGS-VALUES
            PCL::*SUBTYPEP PCL::CLASS-APPLICABLE-USING-CLASS-P
            PCL::SAUT-AND PCL::SAUT-NOT PCL::SAUT-CLASS
            PCL::SAUT-PROTOTYPE PCL::SAUT-CLASS-EQ PCL::SAUT-EQL
            PCL::SPECIALIZER-APPLICABLE-USING-TYPE-P PCL::*TYPEP
            COMPILER::CAN-USE-PRINT-CIRCLE-P1 PCL::DESTRUCTURE
            PCL::INVOKE-EMF PCL:SLOT-BOUNDP PCL:SLOT-EXISTS-P
            PCL:SLOT-MAKUNBOUND PCL:SLOT-VALUE
            PCL::COMPUTE-STD-CPL-PHASE-1 PCL::SLOT-UNBOUND-INTERNAL)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T *) T) PCL::PV-TABLE-LOOKUP-PV-ARGS
            WALKER::RELIST* WALKER::RELIST PCL::FIND-CLASS-PREDICATE
            PCL::EXPAND-MAKE-INSTANCE-FORM PCL::SET-DFUN
            PCL::MAKE-WRAPPER PCL::MAKE-SPECIALIZABLE
            PCL::MAKE-FINAL-DFUN WALKER::WALKER-ENVIRONMENT-BIND-1
            PCL::USE-DISPATCH-DFUN-P PCL::ALLOCATE-STRUCTURE-INSTANCE
            PCL::ALLOCATE-STANDARD-INSTANCE ITERATE::FUNCTION-LAMBDA-P
            ITERATE::MAYBE-WARN PCL::REAL-USE-DISPATCH-DFUN-P
            PCL::MAKE-TYPE-PREDICATE-NAME PCL::USE-CONSTANT-VALUE-DFUN-P
            PCL::ALLOCATE-FUNCALLABLE-INSTANCE
            PCL::GET-MAKE-INSTANCE-FUNCTIONS PCL:FIND-CLASS
            PCL::EARLY-METHOD-SPECIALIZERS
            PCL::INITIALIZE-METHOD-FUNCTION PCL::TRACE-METHOD
            PCL::UPDATE-DFUN PCL::FIND-CLASS-CELL)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T) (*)) PCL::SORT-APPLICABLE-METHODS
            PCL::SORT-METHODS)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T) T) PCL::CPL-INCONSISTENT-ERROR
            WALKER::NOTE-DECLARATION WALKER::NOTE-LEXICAL-BINDING
            PCL::MAKE-PV-TABLE-INTERNAL PCL::FIND-SLOT-DEFINITION
            WALKER::ENVIRONMENT-FUNCTION PCL::|SETF PCL FIND-CLASS|
            PCL::|SETF PCL FIND-CLASS-PREDICATE|
            PCL::COMPUTE-EMF-FROM-WRAPPERS PCL::COMPUTE-PV
            PCL::COMPUTE-CALLS PCL::UPDATE-ALL-PV-TABLE-CACHES
            PCL::MAP-PV-TABLE-REFERENCES-OF
            PCL::GF-MAKE-FUNCTION-FROM-EMF PCL::PLIST-VALUE
            PCL::ADD-DIRECT-SUBCLASSES PCL::UPDATE-CLASS
            PCL::MAKE-CLASS-PREDICATE PCL::ADD-SLOT-ACCESSORS
            PCL::SYMBOL-LESSP PCL::REDEFINE-FUNCTION
            PCL::METHOD-FUNCTION-RETURNING-NIL
            PCL::REMOVE-DIRECT-SUBCLASSES
            PCL::METHOD-FUNCTION-RETURNING-T PCL::SYMBOL-OR-CONS-LESSP
            PCL::REMOVE-SLOT-ACCESSORS
            PCL:FUNCALLABLE-STANDARD-INSTANCE-ACCESS
            PCL::PV-TABLE-LOOKUP PCL::UPDATE-CPL
            PCL::PV-WRAPPERS-FROM-ALL-ARGS PCL::UPDATE-SLOTS
            PCL::UPDATE-INITS PCL::EMIT-1-NIL-DLAP
            PCL::EMIT-1-WRAPPER-COMPUTE-PRIMARY-CACHE-LOCATION
            PCL::COMPUTE-LAYOUT
            PCL::EMIT-N-WRAPPER-COMPUTE-PRIMARY-CACHE-LOCATION
            PCL::GET-MAKE-INSTANCE-FUNCTION-KEY
            PCL::CHANGE-CLASS-INTERNAL PCL::NEW-ARG-INFO-FROM-METHOD
            PCL::ADD-ARG-INFO PCL::REMOVE-ARG-INFO
            PCL:SET-FUNCALLABLE-INSTANCE-FUNCTION PCL::LIST-EQ
            PCL::COMPUTE-APPLICABLE-METHODS-FUNCTION
            PCL::UPDATE-INITIALIZE-INFO-INTERNAL
            PCL::PV-WRAPPERS-FROM-ALL-WRAPPERS
            PCL::UPDATE-STD-OR-STR-METHODS
            PCL::SET-STANDARD-SVUC-METHOD
            PCL::SET-STRUCTURE-SVUC-METHOD
            PCL::|SETF PCL METHOD-FUNCTION-PLIST|
            PCL::MEC-ALL-CLASSES-INTERNAL PCL::MEC-ALL-CLASSES
            PCL::MEC-ALL-CLASS-LISTS PCL:STANDARD-INSTANCE-ACCESS
            PCL::DESCRIBE-PACKAGE PCL::METHODS-CONVERTER
            PCL::RAISE-METATYPE
            PCL::MAKE-DISCRIMINATING-FUNCTION-ARGLIST
            PCL::|SETF PCL GDEFINITION| PCL::NET-CONSTANT-CONVERTER
            PCL::AUGMENT-TYPE PCL::SET-FUNCTION-PRETTY-ARGLIST
            PCL::DOCTOR-DFUN-FOR-THE-DEBUGGER PCL::VALUE-FOR-CACHING
            PCL::ACCESSOR-MISS-FUNCTION PCL::MAKE-UNORDERED-METHODS-EMF
            PCL::FIND-STANDARD-II-METHOD PCL::N-N-DFUN-INFO
            PCL::CHECKING-DFUN-INFO
            PCL::CPL-FORWARD-REFERENCED-CLASS-ERROR
            PCL::MAKE-DFUN-LAMBDA-LIST PCL::MAKE-DLAP-LAMBDA-LIST
            WALKER::ENVIRONMENT-MACRO PCL::MAKE-DFUN-ARG-LIST
            PCL::MAKE-FAST-METHOD-CALL-LAMBDA-LIST ITERATE::MV-SETQ
            ITERATE::EXTRACT-SPECIAL-BINDINGS
            WALKER::VARIABLE-SYMBOL-MACRO-P PCL::ADD-FORMS
            PCL::SET-WRAPPER PCL::BOOTSTRAP-SLOT-INDEX
            PCL::CLASS-CAN-PRECEDE-P PCL::SWAP-WRAPPERS-AND-SLOTS
            PCL::ADD-TO-CVECTOR PCL::SAUT-NOT-CLASS
            PCL::CANONICALIZE-SLOT-SPECIFICATION PCL::SAUT-NOT-CLASS-EQ
            PCL::CANONICALIZE-DEFCLASS-OPTION PCL::SAUT-NOT-PROTOTYPE
            WALKER::WALK-REPEAT-EVAL PCL::%SET-CCLOSURE-ENV
            PCL::SAUT-NOT-EQL PCL::SUPERCLASSES-COMPATIBLE-P
            ITERATE::SIMPLE-EXPAND-ITERATE-FORM
            PCL::CLASSES-HAVE-COMMON-SUBCLASS-P PCL::FDEFINE-CAREFULLY
            PCL::CLASS-MIGHT-PRECEDE-P PCL::NO-SLOT
            PCL::DO-SATISFIES-DEFTYPE PCL::QUALIFIER-CHECK-RUNTIME
            PCL::DEAL-WITH-ARGUMENTS-OPTION
            PCL::MAKE-INTERNAL-READER-METHOD-FUNCTION
            PCL::PARSE-QUALIFIER-PATTERN
            PCL::MAKE-STD-READER-METHOD-FUNCTION
            PCL::MAKE-STD-WRITER-METHOD-FUNCTION
            PCL::MAKE-STD-BOUNDP-METHOD-FUNCTION
            SYSTEM:%SET-COMPILED-FUNCTION-NAME PCL:ADD-METHOD
            SYSTEM::DISPLAY-ENV PCL::PRINTING-RANDOM-THING-INTERNAL
            SYSTEM::DISPLAY-COMPILED-ENV PCL::PROCLAIM-DEFGENERIC
            PCL::COMPUTE-STD-CPL PCL::MAKE-PLIST PCL::REMTAIL
            PCL::MEMF-CONSTANT-CONVERTER PCL::DESTRUCTURE-INTERNAL
            PCL:REMOVE-METHOD PCL::STANDARD-COMPUTE-EFFECTIVE-METHOD
            PCL::SET-METHODS PCL::VARIABLE-CLASS PCL::MAKE-CAXR
            PCL::MAKE-CDXR PCL::REDIRECT-EARLY-FUNCTION-INTERNAL
            WALKER:VARIABLE-LEXICAL-P WALKER:VARIABLE-SPECIAL-P
            PCL::REAL-REMOVE-METHOD PCL::COMPUTE-CONSTANTS)) 
(PROCLAIM '(FTYPE (FUNCTION NIL FIXNUM) PCL::GET-WRAPPER-CACHE-NUMBER)) 
(IN-PACKAGE "PCL")

(DOLIST (PCL::V '(PCL::ADD-READER-METHOD
                     PCL::SHORT-COMBINATION-IDENTITY-WITH-ONE-ARGUMENT
                     PCL::|DEFINITION-SOURCE-MIXIN class predicate|
                     PCL::REMOVE-READER-METHOD PCL::EQL-SPECIALIZER-P
                     PCL::OBJECT-PLIST
                     PCL::SLOT-DEFINITION-DEFSTRUCT-ACCESSOR-SYMBOL
                     PCL::SPECIALIZER-TYPE PCL::GF-DFUN-STATE
                     PCL::CLASS-DEFSTRUCT-CONSTRUCTOR
                     PCL::METHOD-FAST-FUNCTION PCL::SPECIALIZERP
                     PCL::EXACT-CLASS-SPECIALIZER-P
                     PCL::|STANDARD-OBJECT class predicate|
                     PCL::COMPATIBLE-META-CLASS-CHANGE-P
                     PCL::|STANDARD-METHOD-COMBINATION class predicate|
                     PCL::UPDATE-GF-DFUN
                     PCL::|STANDARD-EFFECTIVE-SLOT-DEFINITION class predicate|
                     PCL::SPECIALIZER-OBJECT
                     PCL::ACCESSOR-METHOD-SLOT-NAME
                     PCL::|STANDARD-DIRECT-SLOT-DEFINITION class predicate|
                     PCL::SPECIALIZER-CLASS PCL::CLASS-EQ-SPECIALIZER-P
                     PCL::SLOTS-FETCHER PCL::REMOVE-WRITER-METHOD
                     PCL::|STANDARD-SLOT-DEFINITION class predicate|
                     PCL::STRUCTURE-CLASS-P PCL::UPDATE-CONSTRUCTORS
                     PCL::DOCUMENTATION
                     PCL::|SLOT-OBJECT class predicate|
                     PCL::METHOD-PRETTY-ARGLIST
                     PCL::|RATIONAL class predicate|
                     PCL::CLASS-EQ-SPECIALIZER
                     PCL::INFORM-TYPE-SYSTEM-ABOUT-CLASS
                     PCL::|PCL-CLASS class predicate|
                     PCL::ACCESSOR-METHOD-CLASS
                     PCL::GENERIC-FUNCTION-PRETTY-ARGLIST
                     PCL::MAKE-BOUNDP-METHOD-FUNCTION
                     PCL::|SLOT-DEFINITION class predicate|
                     PCL::|METAOBJECT class predicate|
                     PCL::CLASS-PREDICATE-NAME
                     PCL::|SEQUENCE class predicate| PCL::CLASSP
                     PCL::|CHARACTER class predicate|
                     PCL::|COMPLEX class predicate|
                     PCL::|STD-CLASS class predicate|
                     PCL::LEGAL-QUALIFIERS-P PCL::ADD-BOUNDP-METHOD
                     PCL::LEGAL-LAMBDA-LIST-P
                     PCL::|SETF PCL GENERIC-FUNCTION-NAME|
                     PCL::|DEPENDENT-UPDATE-MIXIN class predicate|
                     PCL::DESCRIBE-OBJECT
                     PCL::MAKE-WRITER-METHOD-FUNCTION
                     PCL::|SETF PCL GF-DFUN-STATE|
                     PCL::|LONG-METHOD-COMBINATION class predicate|
                     PCL::|VECTOR class predicate|
                     PCL::|SETF PCL SLOT-DEFINITION-NAME|
                     PCL::|SETF PCL CLASS-NAME|
                     PCL::INITIALIZE-INTERNAL-SLOT-FUNCTIONS
                     PCL::|SETF PCL SLOT-DEFINITION-TYPE|
                     PCL::METHOD-COMBINATION-P
                     PCL::|STRUCTURE-DIRECT-SLOT-DEFINITION class predicate|
                     PCL::|STRUCTURE-EFFECTIVE-SLOT-DEFINITION class predicate|
                     PCL::|SETF PCL GENERIC-FUNCTION-METHODS|
                     PCL::|SETF PCL GENERIC-FUNCTION-METHOD-COMBINATION|
                     PCL::|SETF PCL METHOD-GENERIC-FUNCTION|
                     PCL::|SETF PCL SLOT-ACCESSOR-STD-P|
                     PCL::LEGAL-SPECIALIZERS-P
                     PCL::|SETF PCL OBJECT-PLIST|
                     PCL::|SETF PCL SLOT-DEFINITION-INITFORM|
                     PCL::|SETF PCL CLASS-DEFSTRUCT-FORM|
                     PCL::|SETF PCL GENERIC-FUNCTION-METHOD-CLASS|
                     PCL::SLOT-ACCESSOR-STD-P
                     PCL::|SETF PCL GF-PRETTY-ARGLIST|
                     PCL::|SETF PCL SLOT-ACCESSOR-FUNCTION|
                     PCL::|SETF PCL SLOT-DEFINITION-LOCATION|
                     PCL::|SETF PCL SLOT-DEFINITION-READER-FUNCTION|
                     PCL::|SETF PCL SLOT-DEFINITION-WRITER-FUNCTION|
                     PCL::|SETF PCL SLOT-DEFINITION-BOUNDP-FUNCTION|
                     PCL::|SETF PCL SLOT-DEFINITION-INTERNAL-READER-FUNCTION|
                     PCL::|SETF PCL SLOT-DEFINITION-INTERNAL-WRITER-FUNCTION|
                     PCL::|SETF PCL SLOT-DEFINITION-ALLOCATION|
                     PCL::|SETF PCL SLOT-DEFINITION-INITFUNCTION|
                     PCL::METHOD-COMBINATION-OPTIONS
                     PCL::|SETF PCL SLOT-DEFINITION-READERS|
                     PCL::|STRUCTURE-OBJECT class predicate|
                     PCL::|SETF PCL DOCUMENTATION|
                     PCL::FUNCALLABLE-STANDARD-CLASS-P
                     PCL::|SETF PCL SLOT-DEFINITION-CLASS|
                     PCL::|SETF PCL SLOT-VALUE-USING-CLASS|
                     PCL::CLASS-CAN-PRECEDE-LIST
                     PCL::|SETF PCL CLASS-DIRECT-SLOTS|
                     PCL::|SETF PCL CLASS-SLOTS|
                     PCL::SLOT-ACCESSOR-FUNCTION
                     PCL::|SETF PCL CLASS-INCOMPATIBLE-SUPERCLASS-LIST|
                     PCL::|SETF PCL SLOT-DEFINITION-WRITERS|
                     PCL::|STRUCTURE-SLOT-DEFINITION class predicate|
                     PCL::SLOT-CLASS-P PCL::MAKE-READER-METHOD-FUNCTION
                     PCL::|STRING class predicate|
                     PCL::LEGAL-METHOD-FUNCTION-P
                     PCL::|NUMBER class predicate| PCL::GET-METHOD
                     PCL::SHORT-METHOD-COMBINATION-P PCL::GF-ARG-INFO
                     PCL::|SYMBOL class predicate|
                     PCL::SPECIALIZER-METHOD-TABLE
                     PCL::MAKE-METHOD-INITARGS-FORM
                     PCL::CLASS-DEFSTRUCT-FORM PCL::GF-PRETTY-ARGLIST
                     PCL::SAME-SPECIALIZER-P
                     PCL::SLOT-DEFINITION-BOUNDP-FUNCTION
                     PCL::SLOT-DEFINITION-WRITER-FUNCTION
                     PCL::SLOT-DEFINITION-READER-FUNCTION
                     PCL::SLOT-DEFINITION-INTERNAL-WRITER-FUNCTION
                     PCL::SLOT-DEFINITION-INTERNAL-READER-FUNCTION
                     PCL::SLOT-DEFINITION-CLASS
                     PCL::EQL-SPECIALIZER-OBJECT
                     PCL::|RATIO class predicate|
                     PCL::CLASS-CONSTRUCTORS PCL::SLOTS-TO-INSPECT
                     PCL::SPECIALIZER-DIRECT-GENERIC-FUNCTIONS
                     PCL::ADD-WRITER-METHOD
                     PCL::MAYBE-UPDATE-CONSTRUCTORS
                     PCL::|EFFECTIVE-SLOT-DEFINITION class predicate|
                     PCL::|LIST class predicate|
                     PCL::LONG-METHOD-COMBINATION-FUNCTION
                     PCL::|BUILT-IN-CLASS class predicate|
                     PCL::GENERIC-FUNCTION-P PCL::|T class predicate|
                     PCL::|FLOAT class predicate|
                     PCL::|CONS class predicate| PCL::LEGAL-SLOT-NAME-P
                     PCL::CLASS-WRAPPER PCL::|ARRAY class predicate|
                     PCL::DEFINITION-SOURCE PCL::DEFAULT-INITARGS
                     PCL::|NULL class predicate| PCL::CLASS-SLOT-VALUE
                     PCL::FORWARD-REFERENCED-CLASS-P
                     PCL::GF-FAST-METHOD-FUNCTION-P
                     PCL::|SPECIALIZER-WITH-OBJECT class predicate|
                     PCL::LEGAL-QUALIFIER-P PCL::METHOD-P
                     PCL::|PLIST-MIXIN class predicate|
                     PCL::CLASS-SLOT-CELLS
                     PCL::STANDARD-ACCESSOR-METHOD-P
                     PCL::STANDARD-GENERIC-FUNCTION-P
                     PCL::STANDARD-READER-METHOD-P
                     PCL::STANDARD-METHOD-P
                     PCL::|TRACED-METHOD class predicate|
                     PCL::COMPUTE-EFFECTIVE-SLOT-DEFINITION-INITARGS
                     PCL::COMPUTE-DEFAULT-INITARGS
                     PCL::|SETF PCL CLASS-SLOT-VALUE|
                     PCL::METHOD-COMBINATION-TYPE PCL::STANDARD-CLASS-P
                     PCL::LEGAL-SPECIALIZER-P
                     PCL::COMPUTE-SLOT-ACCESSOR-INFO
                     PCL::|DIRECT-SLOT-DEFINITION class predicate|
                     PCL::STANDARD-BOUNDP-METHOD-P
                     PCL::RAW-INSTANCE-ALLOCATOR
                     PCL::|SETF PCL SLOT-DEFINITION-DEFSTRUCT-ACCESSOR-SYMBOL|
                     PCL::COMPUTE-DISCRIMINATING-FUNCTION-ARGLIST-INFO
                     PCL::STANDARD-WRITER-METHOD-P
                     PCL::CLASS-INCOMPATIBLE-SUPERCLASS-LIST
                     PCL::WRAPPER-FETCHER
                     PCL::|INTEGER class predicate|
                     PCL::METHOD-COMBINATION-DOCUMENTATION
                     PCL::|SETF PCL SLOT-DEFINITION-INITARGS|
                     PCL::REMOVE-BOUNDP-METHOD
                     PCL::|SETF PCL CLASS-DEFSTRUCT-CONSTRUCTOR|
                     PCL::|DOCUMENTATION-MIXIN class predicate|
                     PCL::SHORT-COMBINATION-OPERATOR
                     PCL::|BIT-VECTOR class predicate|
                     PCL::REMOVE-NAMED-METHOD
                     PCL::LEGAL-DOCUMENTATION-P
                     PCL:CLASS-DIRECT-SUPERCLASSES
                     PCL:CLASS-DIRECT-SUBCLASSES
                     PCL:CLASS-DIRECT-DEFAULT-INITARGS
                     PCL:SLOT-DEFINITION-READERS
                     PCL:SLOT-VALUE-USING-CLASS
                     PCL:COMPUTE-APPLICABLE-METHODS PCL:CLASS-NAME
                     PCL:CLASS-PROTOTYPE PCL:READER-METHOD-CLASS
                     PCL:REMOVE-METHOD PCL:SLOT-DEFINITION-INITFORM
                     PCL:UPDATE-INSTANCE-FOR-REDEFINED-CLASS
                     PCL:UPDATE-INSTANCE-FOR-DIFFERENT-CLASS
                     PCL:CHANGE-CLASS PCL:METHOD-FUNCTION
                     PCL:DIRECT-SLOT-DEFINITION-CLASS
                     PCL:MAKE-METHOD-LAMBDA
                     PCL:EFFECTIVE-SLOT-DEFINITION-CLASS
                     PCL:CLASS-SLOTS PCL:COMPUTE-SLOTS
                     PCL:SLOT-DEFINITION-NAME PCL:FINALIZE-INHERITANCE
                     PCL:GENERIC-FUNCTION-LAMBDA-LIST
                     PCL:CLASS-DIRECT-SLOTS PCL:CLASS-DEFAULT-INITARGS
                     PCL:COMPUTE-DISCRIMINATING-FUNCTION
                     PCL:CLASS-FINALIZED-P PCL:GENERIC-FUNCTION-NAME
                     PCL:REMOVE-DEPENDENT
                     PCL:COMPUTE-CLASS-PRECEDENCE-LIST
                     PCL:ADD-DEPENDENT PCL:SLOT-BOUNDP-USING-CLASS
                     PCL:ACCESSOR-METHOD-SLOT-DEFINITION
                     PCL:SHARED-INITIALIZE PCL:ADD-DIRECT-METHOD
                     PCL:SLOT-DEFINITION-LOCATION
                     PCL:SLOT-DEFINITION-INITFUNCTION
                     PCL:SLOT-DEFINITION-ALLOCATION PCL:ADD-METHOD
                     PCL:GENERIC-FUNCTION-METHOD-CLASS
                     PCL:METHOD-SPECIALIZERS
                     PCL:SLOT-DEFINITION-INITARGS
                     PCL:WRITER-METHOD-CLASS PCL:ADD-DIRECT-SUBCLASS
                     PCL:SPECIALIZER-DIRECT-METHODS
                     PCL:GENERIC-FUNCTION-METHOD-COMBINATION
                     PCL:ALLOCATE-INSTANCE PCL:COMPUTE-EFFECTIVE-METHOD
                     PCL:SLOT-DEFINITION-TYPE PCL:SLOT-UNBOUND
                     PCL:INITIALIZE-INSTANCE PCL:FUNCTION-KEYWORDS
                     PCL:REINITIALIZE-INSTANCE PCL:VALIDATE-SUPERCLASS
                     PCL:GENERIC-FUNCTION-METHODS
                     PCL:REMOVE-DIRECT-METHOD PCL:METHOD-LAMBDA-LIST
                     PCL:MAKE-INSTANCE
                     PCL:COMPUTE-EFFECTIVE-SLOT-DEFINITION
                     PCL:PRINT-OBJECT PCL:METHOD-QUALIFIERS
                     PCL:METHOD-GENERIC-FUNCTION
                     PCL:REMOVE-DIRECT-SUBCLASS
                     PCL:MAKE-INSTANCES-OBSOLETE
                     PCL:SLOT-MAKUNBOUND-USING-CLASS
                     PCL:ENSURE-GENERIC-FUNCTION-USING-CLASS
                     PCL:SLOT-MISSING PCL:MAP-DEPENDENTS
                     PCL:FIND-METHOD-COMBINATION
                     PCL:ENSURE-CLASS-USING-CLASS
                     PCL:NO-APPLICABLE-METHOD
                     PCL:SLOT-DEFINITION-WRITERS
                     PCL:COMPUTE-APPLICABLE-METHODS-USING-CLASSES
                     PCL:CLASS-PRECEDENCE-LIST))
  (SETF (GET PCL::V 'COMPILER::PROCLAIMED-CLOSURE) T)) 
