
(IN-PACKAGE "PCL") 
(PROCLAIM '(FTYPE (FUNCTION (*) FIXNUM) ZERO)) 
(PROCLAIM
    '(FTYPE (FUNCTION (FIXNUM T FIXNUM) FIXNUM)
            COMPUTE-PRIMARY-CACHE-LOCATION-FROM-LOCATION)) 
(PROCLAIM '(FTYPE (FUNCTION (T) CACHE) ISL-CACHE)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) FIXNUM) ARG-INFO-NUMBER-REQUIRED
            DEFAULT-LIMIT-FN CACHE-COUNT CACHING-LIMIT-FN
            ONE-INDEX-LIMIT-FN N-N-ACCESSORS-LIMIT-FN CHECKING-LIMIT-FN
            CACHE-NLINES CACHE-MAX-LOCATION CACHE-MASK
            PV-CACHE-LIMIT-FN CACHE-SIZE EARLY-CLASS-SIZE)) 
(PROCLAIM '(FTYPE (FUNCTION (T) FIELD-TYPE) CACHE-FIELD)) 
(PROCLAIM '(FTYPE (FUNCTION (T) FUNCTION) CACHE-LIMIT-FN)) 
(PROCLAIM '(FTYPE (FUNCTION (FIXNUM) T) POWER-OF-TWO-CEILING)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) LIST) CACHE-OVERFLOW ISL-SLOT-NAME-LISTS)) 
(PROCLAIM '(FTYPE (FUNCTION (T) (MEMBER NIL T)) CACHE-VALUEP)) 
(PROCLAIM '(FTYPE (FUNCTION (T) SIMPLE-VECTOR) CACHE-VECTOR)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) (VALUES T T)) METHOD-FUNCTION-PLIST
            MAKE-CLASS-PREDICATE-NAME LAP-REG MAKE-KEYWORD)) 
(PROCLAIM '(FTYPE (FUNCTION (FIXNUM T) T) %CCLOSURE-ENV-NTHCDR)) 
(PROCLAIM
    '(FTYPE (FUNCTION (FIXNUM FIXNUM T) FIXNUM)
            COMPUTE-PRIMARY-CACHE-LOCATION)) 
(PROCLAIM '(FTYPE (FUNCTION (T) (INTEGER 1 512)) CACHE-LINE-SIZE)) 
(PROCLAIM '(FTYPE (FUNCTION (T) (INTEGER 1 256)) CACHE-NKEYS)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T T T T) *)
            BOOTSTRAP-INITIALIZE-BUILT-IN-CLASS)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T) *) SET-SLOT-VALUE EMIT-READER/WRITER
            ACCESSOR-VALUES CONVERT-METHODS WALKER::WALK-LET-IF
            SLOT-VALUE-USING-CLASS-DFUN SLOT-BOUNDP-USING-CLASS-DFUN
            NET-CODE-CONVERTER WALKER::WALK-FORM-INTERNAL
            ITERATE::EXPAND-INTO-LET CACHE-MISS-VALUES
            ITERATE::RENAME-VARIABLES ITERATE::WALK-GATHERING-BODY
            MAKE-OPTIMIZED-STD-READER-METHOD-FUNCTION
            MAKE-OPTIMIZED-STD-WRITER-METHOD-FUNCTION
            MAKE-OPTIMIZED-STD-BOUNDP-METHOD-FUNCTION
            GET-CLASS-SLOT-VALUE-1 SET-CONSTRUCTOR-CODE
            OPTIMIZE-SLOT-VALUE-BY-CLASS-P
            GET-OPTIMIZED-STD-ACCESSOR-METHOD-FUNCTION
            GET-OPTIMIZED-STD-SLOT-VALUE-USING-CLASS-METHOD-FUNCTION
            MAKE-FINAL-N-N-ACCESSOR-DFUN MAKE-FINAL-CACHING-DFUN
            MAKE-FINAL-CONSTANT-VALUE-DFUN CONSTANT-VALUE-MISS
            LOAD-LONG-DEFCOMBIN CACHING-MISS CHECKING-MISS)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T T T T T T T T) *)
            BOOTSTRAP-INITIALIZE-STANDARD-CLASS)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T) *)
            GENERATE-DISCRIMINATION-NET-INTERNAL
            MAKE-LONG-METHOD-COMBINATION-FUNCTION
            DO-SHORT-METHOD-COMBINATION GENERAL-GENERATOR-INTERNAL
            REAL-LOAD-DEFCLASS)) 
(PROCLAIM '(FTYPE (FUNCTION (T T T T T T *) *) REAL-MAKE-A-METHOD)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T) *) ACCESSOR-MISS
            GENERATE-DISCRIMINATION-NET
            SETF-SLOT-VALUE-USING-CLASS-DFUN ORDER-SPECIALIZERS
            FINALIZE-LAP-GENERATION MAKE-ONE-CLASS-ACCESSOR-DFUN
            MAKE-FINAL-ONE-INDEX-ACCESSOR-DFUN SET-CLASS-SLOT-VALUE-1
            MAKE-CONSTRUCTOR GET-ACCESSOR-FROM-SVUC-METHOD-FUNCTION
            GET-ACCESSOR-METHOD-FUNCTION NO-METHODS-GENERATOR-INTERNAL
            MAKE-FINAL-CHECKING-DFUN SIMPLE-SLOTS-GENERATOR-INTERNAL
            LOAD-SHORT-DEFCOMBIN)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T) *)
            COMPUTE-DISCRIMINATING-FUNCTION-ARGLIST-INFO-INTERNAL
            MAKE-TWO-CLASS-ACCESSOR-DFUN EXPAND-DEFMETHOD-INTERNAL)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T *) *) TYPES-FROM-ARGUMENTS
            GET-EFFECTIVE-METHOD-FUNCTION MAKE-ACCESSOR-TABLE
            MAKE-CHECKING-DFUN LOAD-DEFGENERIC MAKE-N-N-ACCESSOR-DFUN
            COMPUTE-SECONDARY-DISPATCH-FUNCTION
            MAKE-EFFECTIVE-METHOD-FUNCTION SLOT-VALUE-OR-DEFAULT
            NESTED-WALK-FORM)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T T) *) MAKE-LAP-CLOSURE-GENERATOR
            ITERATE::ITERATE-TRANSFORM-BODY)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T *) *) GET-SECONDARY-DISPATCH-FUNCTION
            MAKE-ONE-INDEX-ACCESSOR-DFUN WALKER::WALK-DECLARATIONS)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T *) *) ITERATE::RENAME-LET-BINDINGS)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T T T) *)
            BOOTSTRAP-INITIALIZE-STRUCTURE-CLASS)) 
(PROCLAIM '(FTYPE (FUNCTION (T STREAM T) T) PRINT-DFUN-INFO)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T) T) BOOTSTRAP-ACCESSOR-DEFINITIONS
            FILL-CACHE-P ADJUST-CACHE EXPAND-CACHE
            EMIT-CHECK-2-CLASS-WRAPPER EMIT-CHECK-1-WRAPPER-IN-CACHE
            EMIT-CHECK-CACHE-ENTRY EMIT-CHECK-CACHE-LINE
            GET-WRAPPERS-FROM-CLASSES LOAD-PRECOMPILED-DFUN-CONSTRUCTOR
            WALKER::WALK-TEMPLATE TWO-CLASS-DFUN-INFO
            WALKER::WALK-LET/LET* WALKER::WALK-PROG/PROG*
            WALKER::WALK-DO/DO* WALKER::WALK-BINDINGS-2 GET-CACHE
            EXPAND-DEFCONSTRUCTOR CHECK-INITARGS EXPAND-DEFCLASS
            EXPAND-SYMBOL-MACROLET-INTERNAL BOOTSTRAP-SET-SLOT)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T *) T) EARLY-ADD-NAMED-METHOD
            REAL-ADD-NAMED-METHOD)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T *) T) SET-ARG-INFO EMIT-DLAP
            EARLY-MAKE-A-METHOD)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T) T) COMPUTE-PRECEDENCE ONE-INDEX-DFUN-INFO
            FLUSH-CACHE-TRAP OBSOLETE-INSTANCE-TRAP |LAP Operand ISET|
            EMIT-CHECK-1-CLASS-WRAPPER CHECK-OPCODE-ARG
            CHECK-OPERAND-ARG WALKER::WALK-PROG* EMIT-LOCK-COUNT-TEST
            |LAP Opcode EQ| |LAP Opcode NEQ| |LAP Opcode FIX=|
            GET-FUNCTION-GENERATOR GET-NEW-FUNCTION-GENERATOR
            WRAP-METHOD-GROUP-SPECIFIER-BINDINGS TRACE-METHOD-INTERNAL
            CONVERT-TABLE FIX-SLOT-ACCESSORS WALKER::WALK-NAMED-LAMBDA
            MAP-ALL-ORDERS WALKER::WITH-AUGMENTED-ENVIRONMENT-INTERNAL
            NEW-ARG-INFO-FROM-GENERIC-FUNCTION ONE-CLASS-DFUN-INFO
            PRINT-CACHE ITERATE::OPTIMIZE-ITERATE-FORM WALKER::RECONS
            WALKER::RELIST-INTERNAL INVALIDATE-WRAPPER
            WALKER::WALK-TAGBODY-1 WALKER::WALK-LAMBDA
            ITERATE::OPTIMIZE-GATHERING-FORM
            EMIT-1-WRAPPER-COMPUTE-PRIMARY-CACHE-LOCATION
            ITERATE::SIMPLE-EXPAND-GATHERING-FORM
            EMIT-N-WRAPPER-COMPUTE-PRIMARY-CACHE-LOCATION
            ITERATE::RENAME-AND-CAPTURE-VARIABLES
            WALKER::WALK-COMPILER-LET ITERATE::VARIABLE-SAME-P
            WALKER::WALK-UNEXPECTED-DECLARE WALKER::WALK-FLET
            WALKER::WALK-IF WALKER::WALK-LABELS WALKER::WALK-LET
            WALKER::WALK-LET* WALKER::WALK-MACROLET
            WALKER::WALK-MULTIPLE-VALUE-SETQ
            WALKER::WALK-MULTIPLE-VALUE-BIND WALKER::WALK-SETQ
            OPTIMIZED-STRUCTURE-SLOT-BOUNDP-USING-CLASS-METHOD-FUNCTION
            MAKE-OPTIMIZED-STD-SLOT-VALUE-USING-CLASS-METHOD-FUNCTION
            WALKER::WALK-SYMBOL-MACROLET WALKER::WALK-TAGBODY
            MAKE-OPTIMIZED-STD-SETF-SLOT-VALUE-USING-CLASS-METHOD-FUNCTION
            MAKE-DFUN-CALL WALKER::WALK-DO
            MAKE-OPTIMIZED-STD-SLOT-BOUNDP-USING-CLASS-METHOD-FUNCTION
            COMPUTE-STD-CPL-PHASE-3 WALKER::WALK-DO* WALKER::WALK-PROG
            SKIP-OPTIMIZE-SLOT-VALUE-BY-CLASS-P SKIP-FAST-SLOT-ACCESS-P
            |SETF PCL METHOD-FUNCTION-GET| VARIABLE-DECLARATION
            |SETF PCL PLIST-VALUE| ENTRY-IN-CACHE-P PRINT-STD-INSTANCE
            EXPAND-DEFGENERIC ADD-PV-BINDING MAKE-METHOD-SPEC
            SET-FUNCTION-NAME-1 DECLARE-STRUCTURE BOOTSTRAP-GET-SLOT
            MAKE-TOP-LEVEL-FORM CAN-OPTIMIZE-ACCESS OPTIMIZE-SLOT-VALUE
            OPTIMIZE-SET-SLOT-VALUE OPTIMIZE-SLOT-BOUNDP
            CHECK-INITARGS-1 OPTIMIZE-GENERIC-FUNCTION-CALL)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T) T) MAKE-LAP-PROG DLAP-WRAPPER-MOVES
            EMIT-1-NIL-DLAP LOAD-FUNCTION-GENERATOR
            GET-SECONDARY-DISPATCH-FUNCTION2
            MAKE-FINAL-ORDINARY-DFUN-INTERNAL MAKE-FGEN
            WALKER::WALK-TEMPLATE-HANDLE-REPEAT MAKE-EMF-CACHE
            WALKER::WALK-BINDINGS-1 OPTIMIZE-INSTANCE-ACCESS
            |CONSTRUCTOR-CODE-GENERATOR PCL FALLBACK|
            |CONSTRUCTOR-CODE-GENERATOR PCL GENERAL|
            |CONSTRUCTOR-CODE-GENERATOR PCL NO-METHODS|
            |CONSTRUCTOR-CODE-GENERATOR PCL SIMPLE-SLOTS|
            MAKE-LAP-PROG-INTERNAL LOAD-CONSTRUCTOR
            MAKE-PARAMETER-REFERENCES BOOTSTRAP-MAKE-SLOT-DEFINITIONS)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T *) T) GET-SECONDARY-DISPATCH-FUNCTION1
            EMIT-GET-SLOT EMIT-SET-SLOT WALKER::WALK-ARGLIST FILL-CACHE
            REAL-GET-METHOD GET-METHOD)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T) T) BOOTSTRAP-MAKE-SLOT-DEFINITION
            EMIT-DLAP-INTERNAL EMIT-GREATER-THAN-1-DLAP EMIT-1-T-DLAP
            EMIT-ADJUST-LOCATION WALKER::WALK-TEMPLATE-HANDLE-REPEAT-1
            EXPAND-DEFMETHOD LOAD-DEFCLASS MAKE-EARLY-CLASS-DEFINITION)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T *) T) NAMED-OBJECT-PRINT-FUNCTION
            REAL-ENSURE-GF-USING-CLASS--GENERIC-FUNCTION
            REAL-ENSURE-GF-USING-CLASS--NULL EMIT-GET-CLASS-SLOT
            EMIT-SET-CLASS-SLOT GET-CACHE-FROM-CACHE
            GET-EFFECTIVE-METHOD-FUNCTION1
            WALKER::CONVERT-MACRO-TO-LAMBDA CPL-ERROR PROBE-CACHE
            MAP-CACHE FIND-CLASS-FROM-CELL
            FIND-CLASS-PREDICATE-FROM-CELL
            ENSURE-GENERIC-FUNCTION-USING-CLASS RECORD-DEFINITION
            DEFOPCODE-1 DEFOPERAND-1)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T T T T) T) LOAD-DEFMETHOD
            LOAD-DEFMETHOD-INTERNAL)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T T T T T T) T)
            ADD-LEXICAL-FUNCTIONS-TO-METHOD-LAMBDA)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T T) T)
            MAKE-LAP-CLOSURE-GENERATOR-LAMBDA)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T *) T) FILL-DFUN-CACHE
            EMIT-FETCH-WRAPPER)) 
(PROCLAIM '(FTYPE (FUNCTION (T T T FIXNUM) T) FILL-CACHE-FROM-CACHE-P)) 
(PROCLAIM
    '(FTYPE (FUNCTION NIL *) EMIT-N-N-READERS EMIT-N-N-WRITERS
            COUNT-ALL-DFUNS)) 
(PROCLAIM
    '(FTYPE (FUNCTION NIL T) SHOW-DFUN-CONSTRUCTORS
            BOOTSTRAP-META-BRAID MAKE-CACHE EARLY-INITIALIZE-SLOT-GFS
            EARLY-INITIALIZE-CLASS-PREDICATES
            BOOTSTRAP-BUILT-IN-CLASSES RESET-PCL-PACKAGE
            |LAP Opcode BREAK| |LAP Opcode BEEP| DISPATCH-DFUN-INFO
            SHOW-FREE-CACHE-VECTORS DEFAULT-METHOD-ONLY-DFUN-INFO
            RENEW-SYS-FILES GET-EFFECTIVE-METHOD-GENSYM
            RESET-CONSTRUCTORS MAKE-CPD LIST-ALL-DFUNS
            DISABLE-CONSTRUCTORS ENABLE-CONSTRUCTORS CACHES-TO-ALLOCATE
            ALLOCATE-FUNCALLABLE-INSTANCE-2
            ALLOCATE-FUNCALLABLE-INSTANCE-1 %%ALLOCATE-INSTANCE--CLASS
            BEFORE-PRECOMPILE-RANDOM-CODE-SEGMENTS MAKE-ARG-INFO
            IN-THE-COMPILER-P STRUCTURE-FUNCTIONS-EXIST-P
            |LAP Opcode EXIT-LAP-IN-LISP|)) 
(PROCLAIM
    '(FTYPE (FUNCTION (*) *) METHOD-COMBINATION-ERROR UNTRACE-METHOD
            PV-WRAPPERS-FROM-PV-ARGS LIST-LARGE-CACHES
            INVALID-METHOD-ERROR)) 
(PROCLAIM '(FTYPE (FUNCTION (FIXNUM T *) *) FIND-FREE-CACHE-LINE)) 
(PROCLAIM '(FTYPE (FUNCTION (FIXNUM T T) *) COMPUTE-CACHE-PARAMETERS)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) *) FIND-WRAPPER STRUCTURE-WRAPPER
            COMPUTE-APPLICABLE-METHODS-EMF SPECIALIZER-FROM-TYPE
            CLASS-EQ-TYPE EMIT-ONE-CLASS-READER EMIT-ONE-CLASS-WRITER
            EMIT-TWO-CLASS-READER EMIT-TWO-CLASS-WRITER
            EMIT-ONE-INDEX-READERS EMIT-ONE-INDEX-WRITERS
            DEFAULT-CODE-CONVERTER EMIT-CONSTANT-VALUE
            PARSE-METHOD-GROUP-SPECIFIER PCL-DESCRIBE
            FORCE-CACHE-FLUSHES GET-DISPATCH-FUNCTION
            MAKE-DISPATCH-DFUN CCLOSUREP MAP-CONSTRUCTORS
            COMPUTE-CONSTANT-VECTOR PARSE-DEFMETHOD
            METHOD-PROTOTYPE-FOR-GF FIND-STRUCTURE-CLASS
            INTERN-SLOT-NAME-LISTS ANALYZE-LAMBDA-LIST
            MAKE-FINAL-DISPATCH-DFUN TYPE-FROM-SPECIALIZER
            *NORMALIZE-TYPE UNPARSE-TYPE CONVERT-TO-SYSTEM-TYPE
            EARLY-COLLECT-INHERITANCE)) 
(PROCLAIM
    '(FTYPE (FUNCTION (*) T) |__si::MAKE-DFUN-INFO|
            FIX-EARLY-GENERIC-FUNCTIONS |__si::MAKE-DISPATCH|
            |__si::MAKE-DEFAULT-METHOD-ONLY|
            |__si::MAKE-ACCESSOR-DFUN-INFO|
            |__si::MAKE-ONE-INDEX-DFUN-INFO| TRUE |__si::MAKE-N-N|
            |__si::MAKE-ONE-CLASS| |__si::MAKE-TWO-CLASS|
            |__si::MAKE-ONE-INDEX| |__si::MAKE-ISL|
            |STRUCTURE-OBJECT class constructor|
            WALKER::UNBOUND-LEXICAL-FUNCTION |__si::MAKE-ARG-INFO|
            |__si::MAKE-CACHE| |__si::MAKE-CHECKING|
            |__si::MAKE-CACHING| |__si::MAKE-CONSTANT-VALUE|
            |__si::MAKE-CLASS-PRECEDENCE-DESCRIPTION|
            |__si::MAKE-STD-INSTANCE| CALLED-FIN-WITHOUT-FUNCTION
            STRING-APPEND FLATTEN-LAP FALSE MAKE-PROGN)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) T) REDIRECT-EARLY-FUNCTION-INTERNAL
            ARG-INFO-VALID-P |LAP Operand OTHER-WRAPPER|
            |LAP Operand BUILT-IN-OR-STRUCTURE-WRAPPER| UPDATE-GF-INFO
            ALLOCATE-CACHE-VECTOR |LAP Operand STD-SLOTS|
            FLUSH-CACHE-VECTOR-INTERNAL |LAP Operand FSC-SLOTS|
            DO-STANDARD-DEFSETFS-FOR-DEFCLASS
            |LAP Operand WRAPPER-CACHE-NUMBER-VECTOR| GET-CACHE-VECTOR
            METHOD-FUNCTION-ISL METHOD-FUNCTION-NEEDS-NEXT-METHODS-P
            FREE-CACHE-VECTOR GDEFINITION DFUN-INFO-P DFUN-ARG-SYMBOL
            EARLY-METHOD-FUNCTION |LAP Operand I1+| EXTRACT-PARAMETERS
            EXTRACT-SPECIALIZER-NAMES DISPATCH-P
            EXTRACT-REQUIRED-PARAMETERS
            DEFAULT-SECONDARY-DISPATCH-FUNCTION FREE-CACHE
            DEFAULT-METHOD-ONLY-P EMIT-MISS UPDATE-C-A-M-GF-INFO
            DLAP-WRAPPERS UPDATE-GF-SIMPLE-ACCESSOR-TYPE
            ACCESSOR-DFUN-INFO-P STANDARD-SVUC-METHOD
            STRUCTURE-SVUC-METHOD TYPE-CLASS ONE-INDEX-DFUN-INFO-P
            CLASS-PREDICATE MAKE-CLASS-EQ-PREDICATE |LAP Operand LISP|
            MAKE-EQL-PREDICATE |LAP Operand LISP-VARIABLE|
            |LAP Opcode PRINT| N-N-P GET-BUILT-IN-CLASS-SYMBOL
            GET-BUILT-IN-WRAPPER-SYMBOL ARG-INFO-NKEYS ONE-CLASS-P
            DEFAULT-TEST-CONVERTER GET-READER-FUNCTION ARG-INFO-APPLYP
            NET-TEST-CONVERTER DEFAULT-CONSTANT-CONVERTER
            METHODS-CONTAIN-EQL-SPECIALIZER-P |LAP Opcode JMP|
            GET-WRITER-FUNCTION |LAP Opcode LABEL| TWO-CLASS-P
            |LAP Opcode GO| DEFAULT-CONSTANTP |LAP Opcode RETURN|
            FGEN-TEST GF-DFUN-CACHE LOOKUP-FGEN EXPAND-LONG-DEFCOMBIN
            FGEN-GENERATOR EXPAND-SHORT-DEFCOMBIN
            UPDATE-ALL-C-A-M-GF-INFO UNDEFMETHOD-1 STORE-FGEN
            FGEN-SYSTEM CONSTANT-VALUE-P FGEN-GENSYMS MAKE-INITIAL-DFUN
            ACCESSOR-DFUN-INFO-ACCESSOR-TYPE FGEN-GENERATOR-LAMBDA
            MAP-SPECIALIZERS MAKE-DEFAULT-METHOD-GROUP-DESCRIPTION
            USE-CONSTANT-VALUE-DFUN-P ONE-INDEX-DFUN-INFO-INDEX
            CLASS-FROM-TYPE CLASS-HAS-A-FORWARD-REFERENCED-SUPERCLASS-P
            ONE-CLASS-WRAPPER0 DNET-METHODS-P TWO-CLASS-WRAPPER1
            CHECKING-FUNCTION UPDATE-GFS-OF-CLASS CACHING-DFUN-INFO
            ALLOCATE-REGISTER UPDATE-CLASS-CAN-PRECEDE-P
            DEALLOCATE-REGISTER COMPUTE-CLASS-SLOTS ARG-INFO-PRECEDENCE
            ARG-INFO-METATYPES UPDATE-ISL-CACHE-INFO
            ARG-INFO-NUMBER-OPTIONAL ARG-INFO-KEY/REST-P
            MAKE-STD-BOUNDP-METHOD-FUNCTION ARG-INFO-KEYWORDS
            GF-INFO-SIMPLE-ACCESSOR-TYPE ISLP CONSTANT-VALUE-DFUN-INFO
            MAKE-STD-WRITER-METHOD-FUNCTION
            GF-PRECOMPUTE-DFUN-AND-EMF-P GF-INFO-STATIC-C-A-M-EMF
            STRUCTURE-OBJECT-P MAKE-STD-READER-METHOD-FUNCTION
            GF-INFO-C-A-M-EMF-STD-P WALKER::ENV-LOCK
            ARG-INFO-LAMBDA-LIST WALKER::ENV-LEXICAL-VARIABLES
            USE-CACHING-DFUN-P WALKER::ENV-DECLARATIONS
            WALKER::GET-IMPLEMENTATION-DEPENDENT-WALKER-TEMPLATE
            ARG-INFO-P WALKER::ENV-WALK-FORM WALKER::ENV-WALK-FUNCTION
            WALKER::GET-WALKER-TEMPLATE CACHE-P GFS-OF-TYPE
            PROCLAIM-INCOMPATIBLE-SUPERCLASSES
            COMPUTE-APPLICABLE-METHODS-EMF-STD-P
            ITERATE::VARIABLES-FROM-LET STRUCTURE-TYPE-INTERNAL-SLOTDS
            MAKE-WRAPPER COPY-CACHE GF-DFUN-INFO
            ITERATE::SEQUENCE-ACCESSOR COMPUTE-LINE-SIZE
            USE-DISPATCH-DFUN-P %CCLOSURE-ENV SLOT-READER-SYMBOL
            SLOT-WRITER-SYMBOL GET-BOUNDP-FUNCTION SLOT-BOUNDP-SYMBOL
            STRUCTURE-SLOT-BOUNDP
            MAKE-OPTIMIZED-STRUCTURE-SLOT-VALUE-USING-CLASS-METHOD-FUNCTION
            MAKE-OPTIMIZED-STRUCTURE-SETF-SLOT-VALUE-USING-CLASS-METHOD-FUNCTION
            SLOT-VECTOR-SYMBOL STRUCTURE-SLOTD-READER-FUNCTION
            COMPUTE-STD-CPL-PHASE-2 MAKE-CALL-METHODS
            MAKE-NOT-FOR-CACHING-METHOD-FUNCTION ONE-INDEX-P CHECKING-P
            FIND-CYCLE-REASONS FORMAT-CYCLE-REASONS CACHING-P CLASS-OF
            MAKE-PERMUTATION-VECTOR CPD-CLASS CPD-SUPERS MUTATE-SLOTS
            SORT-SLOTS CPD-AFTER MAKE-ISL-TYPE-DECLARATION
            MAKE-PV-TYPE-DECLARATION CPD-COUNT SYMBOL-PKG-NAME MAKE-ISL
            VARIABLE-GLOBALLY-SPECIAL-P
            MAKE-INTERNAL-READER-METHOD-FUNCTION STD-INSTANCE-P
            CLASS-PRECEDENCE-DESCRIPTION-P FUNCALLABLE-INSTANCE-P
            DFUN-INFO-CACHE DISPATCH-CACHE DEFAULT-METHOD-ONLY-CACHE
            ACCESSOR-DFUN-INFO-CACHE ONE-INDEX-DFUN-INFO-CACHE
            ONE-INDEX-DFUN-INFO-ACCESSOR-TYPE LAP-OPCODE N-N-CACHE
            FUNCTION-RETURNING-NIL %STD-INSTANCE-WRAPPER
            N-N-ACCESSOR-TYPE LAP-REG-INITIAL-VALUE-FORM
            %STD-INSTANCE-SLOTS ONE-CLASS-CACHE LAP-OPERAND
            ONE-CLASS-ACCESSOR-TYPE ONE-CLASS-INDEX TWO-CLASS-CACHE
            SYSTEM:%STRUCTURE-NAME TWO-CLASS-ACCESSOR-TYPE
            SYSTEM:%COMPILED-FUNCTION-NAME TWO-CLASS-INDEX
            TWO-CLASS-WRAPPER0 ONE-INDEX-CACHE INDEX-VALUE->INDEX
            ONE-INDEX-ACCESSOR-TYPE INDEX->INDEX-VALUE ONE-INDEX-INDEX
            CHECKING-CACHE DO-STANDARD-DEFSETF-1
            INITIALIZE-INTERNAL-SLOT-GFS CACHING-CACHE
            CONSTANT-VALUE-CACHE EXTRACT-LAMBDA-LIST
            WRAPPER-FOR-STRUCTURE SLOT-NAME-LISTS-FROM-SLOTS
            LEGAL-CLASS-NAME-P STRUCTURE-TYPE-P BUILT-IN-WRAPPER-OF
            NON-PCL-OR-AFTER-INITIALIZE-INSTANCE-METHODS-P
            BUILT-IN-OR-STRUCTURE-WRAPPER1
            NON-PCL-OR-AFTER-SHARED-INITIALIZE-METHODS-P SETFBOUNDP
            INTERN-FUNCTION-NAME GET-SETF-FUNCTION-NAME
            COMPILE-LAMBDA-UNCOMPILED KEYWORD-SPEC-NAME
            FTYPE-DECLARATION-FROM-LAMBDA-LIST COMPILE-LAMBDA-DEFERRED
            GENERIC-CLOBBERS-FUNCTION UNENCAPSULATED-FDEFINITION
            FUNCTION-PRETTY-ARGLIST PARSE-SPECIALIZERS
            NON-PCL-INITIALIZE-INSTANCE-METHODS-P
            EARLY-METHOD-QUALIFIERS NON-PCL-SHARED-INITIALIZE-METHODS-P
            INTERN-EQL-SPECIALIZER WRAPPER-FIELD
            EARLY-UPDATE-DISCRIMINATOR-CODE LIST-DFUN
            EARLY-CLASS-DEFINITION NEXT-WRAPPER-FIELD EARLY-GF-P
            MAKE-TYPE-PREDICATE EARLY-GF-NAME |LAP Operand REG|
            LIST-LARGE-CACHE DEFAULT-STRUCTUREP EARLY-COLLECT-CPL
            EARLY-GET-CPL DEFAULT-STRUCTURE-INSTANCE-P
            |LAP Operand CVAR| UNPARSE-TYPE-LIST DEFAULT-STRUCTURE-TYPE
            EARLY-COLLECT-SLOTS |LAP Operand ARG| COUNT-DFUN
            STRUCTURE-TYPE INFORM-TYPE-SYSTEM-ABOUT-STD-CLASS
            EARLY-COLLECT-DEFAULT-INITARGS
            EARLY-METHOD-STANDARD-ACCESSOR-P
            STRUCTURE-TYPE-INCLUDED-TYPE-NAME MAKE-INITFUNCTION
            WRAPPER-OF STRUCTURE-TYPE-SLOT-DESCRIPTION-LIST
            CHECK-WRAPPER-VALIDITY CANONICAL-SLOT-NAME
            STRUCTURE-SLOTD-NAME |LAP Operand CDR|
            MAP-ALL-GENERIC-FUNCTIONS STRUCTURE-SLOTD-ACCESSOR-SYMBOL
            ECD-CLASS-NAME GBOUNDP STRUCTURE-SLOTD-WRITER-FUNCTION
            UNPARSE-SPECIALIZERS GMAKUNBOUND |LAP Operand CONSTANT|
            ECD-SOURCE METHOD-LL->GENERIC-FUNCTION-LL ECD-METACLASS
            ECD-SUPERCLASS-NAMES EARLY-CLASS-SLOTS
            |LAP Operand STD-WRAPPER| ECD-CANONICAL-SLOTS
            ECD-OTHER-INITARGS MAKE-CONSTANT-FUNCTION
            FUNCTION-RETURNING-T |LAP Operand FSC-WRAPPER|
            MAKE-FUNCTION-INLINE |LAP Operand BUILT-IN-WRAPPER|
            |LAP Operand STRUCTURE-WRAPPER|)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T *) *) PARSE-METHOD-OR-SPEC OPCODE OPERAND
            MAKE-FINAL-DFUN-INTERNAL MAP-ALL-CLASSES GET-FUNCTION
            GET-FUNCTION1 MAKE-CONSTANT-VALUE-DFUN GET-DFUN-CONSTRUCTOR
            MAKE-CACHING-DFUN GET-METHOD-FUNCTION
            ENSURE-GENERIC-FUNCTION WALK-FORM EXTRACT-DECLARATIONS
            PARSE-SPECIALIZED-LAMBDA-LIST ENSURE-CLASS COERCE-TO-CLASS
            COMPILE-LAMBDA)) 
(PROCLAIM '(FTYPE (FUNCTION (T T *) (VALUES T T)) SYMBOL-APPEND)) 
(PROCLAIM '(FTYPE (FUNCTION (T *) STRING) CAPITALIZE-WORDS)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T *) T) UPDATE-DFUN SET-DFUN MAKE-FINAL-DFUN
            TRACE-METHOD WALKER::WALKER-ENVIRONMENT-BIND-1
            MAKE-SPECIALIZABLE ITERATE::FUNCTION-LAMBDA-P
            ITERATE::MAYBE-WARN WALKER::RELIST*
            PRECOMPUTE-EFFECTIVE-METHODS WALKER::RELIST FIND-CLASS
            LAP-OPERANDS FIND-CLASS-CELL EARLY-METHOD-SPECIALIZERS
            MAKE-TYPE-PREDICATE-NAME FIND-CLASS-PREDICATE)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T) *) COMPUTE-APPLICABLE-METHODS-USING-TYPES
            CLASS-APPLICABLE-USING-CLASS-P EMIT-WRAPPER-REF SAUT-AND
            SAUT-NOT SAUT-CLASS SAUT-CLASS-EQ SAUT-EQL SLOT-BOUNDP
            SLOT-EXISTS-P SLOT-MAKUNBOUND EMIT-CHECKING EMIT-CACHING
            SLOT-VALUE COMPUTE-TEST UPDATE-SLOT-VALUE-GF-INFO
            GET-NEW-FUNCTION-GENERATOR-INTERNAL COMPUTE-CODE
            SDFUN-FOR-CACHING EMIT-CACHE-VECTOR-REF MAKE-DIRECT-SLOTD
            ITERATE::PARSE-DECLARATIONS COMPUTE-STD-CPL-PHASE-1
            FIND-SUPERCLASS-CHAIN GENERATE-FAST-CLASS-SLOT-ACCESS-P
            ENSURE-CLASS-VALUES DESTRUCTURE SET-FUNCTION-NAME *SUBTYPEP
            SPECIALIZER-APPLICABLE-USING-TYPE-P *TYPEP INITIAL-DFUN
            EARLY-DFUN)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T) (*)) SORT-APPLICABLE-METHODS
            SORT-METHODS)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T) T) |SETF PCL FIND-CLASS-PREDICATE|
            NEW-ARG-INFO-FROM-METHOD ADD-ARG-INFO REAL-REMOVE-METHOD
            REMOVE-ARG-INFO SUPERCLASSES-COMPATIBLE-P
            CLASSES-HAVE-COMMON-SUBCLASS-P METHOD-FUNCTION-GET
            SAUT-NOT-CLASS PLIST-VALUE SAUT-NOT-CLASS-EQ
            |LAP Operand CREF| SAUT-NOT-EQL |LAP Operand IREF|
            REDEFINE-FUNCTION |LAP Operand I+| LIST-EQ |LAP Operand I-|
            COMPUTE-APPLICABLE-METHODS-FUNCTION |LAP Operand ILOGAND|
            QUALIFIER-CHECK-RUNTIME |LAP Operand ILOGXOR|
            |LAP Operand ISHIFT| UPDATE-STD-OR-STR-METHODS
            SET-STANDARD-SVUC-METHOD SET-STRUCTURE-SVUC-METHOD
            MEC-ALL-CLASSES-INTERNAL MEC-ALL-CLASSES
            MEC-ALL-CLASS-LISTS |LAP Opcode MOVE| VARIABLE-CLASS
            REMOVE-METHOD COMPUTE-SECONDARY-DISPATCH-FUNCTION1
            METHODS-CONVERTER |LAP Opcode IZEROP|
            |LAP Opcode STD-INSTANCE-P| |LAP Opcode FSC-INSTANCE-P|
            |LAP Opcode BUILT-IN-INSTANCE-P|
            |LAP Opcode STRUCTURE-INSTANCE-P| COMPUTE-CONSTANTS
            MAKE-EFFECTIVE-METHOD-FUNCTION1 DEAL-WITH-ARGUMENTS-OPTION
            PARSE-QUALIFIER-PATTERN NET-CONSTANT-CONVERTER AUGMENT-TYPE
            UPDATE-CPL UPDATE-SLOTS VALUE-FOR-CACHING
            CLASS-MIGHT-PRECEDE-P UPDATE-INITS UPDATE-CLASS
            MAKE-DISCRIMINATING-FUNCTION-ARGLIST UPDATE-ALL-ISL-CACHES
            WALKER::ENVIRONMENT-MACRO COMPUTE-LAYOUT
            WALKER::VARIABLE-SYMBOL-MACRO-P ACCESSOR-MISS-FUNCTION
            ADD-DIRECT-SUBCLASSES MAKE-CLASS-PREDICATE
            ADD-SLOT-ACCESSORS WALKER::WALK-REPEAT-EVAL N-N-DFUN-INFO
            WALKER::NOTE-DECLARATION ITERATE::MV-SETQ
            WALKER::NOTE-LEXICAL-BINDING REMOVE-DIRECT-SUBCLASSES
            ITERATE::EXTRACT-SPECIAL-BINDINGS REMOVE-SLOT-ACCESSORS
            MAKE-UNORDERED-METHODS-EMF WALKER::ENVIRONMENT-FUNCTION
            NO-SLOT RAISE-METATYPE %SET-CCLOSURE-ENV CHECKING-DFUN-INFO
            ITERATE::SIMPLE-EXPAND-ITERATE-FORM
            MAKE-EFFECTIVE-METHOD-FUNCTION-SIMPLE
            MAKE-EFFECTIVE-METHOD-FUNCTION-INTERNAL COMPUTE-STD-CPL
            MAKE-DFUN-LAMBDA-LIST MAKE-DLAP-LAMBDA-LIST
            CPL-INCONSISTENT-ERROR SET-WRAPPER SET-SLOTS
            PV-WRAPPERS-FROM-ALL-WRAPPERS COMPUTE-INITARG-POSITIONS
            ISL-LOOKUP ADD-METHOD CPL-FORWARD-REFERENCED-CLASS-ERROR
            GET-BOUNDP-FUNCTION1 MAKE-ISL-INTERNAL FIND-SLOT-DEFINITION
            STANDARD-INSTANCE-ACCESS
            FUNCALLABLE-STANDARD-INSTANCE-ACCESS LOOKUP-PV
            |SETF PCL METHOD-FUNCTION-PLIST| VARIABLE-LEXICAL-P
            VARIABLE-SPECIAL-P |SETF PCL GDEFINITION|
            SET-FUNCALLABLE-INSTANCE-FUNCTION
            PRINTING-RANDOM-THING-INTERNAL
            LOAD-DEFINE-CONSTRUCTOR-CODE-TYPE
            SYSTEM:%SET-COMPILED-FUNCTION-NAME
            ALLOCATE-FUNCALLABLE-INSTANCE MAKE-INDEX-MASK MAKE-PLIST
            REMTAIL DESTRUCTURE-INTERNAL MAKE-PV-FN-FORM MAKE-CAXR
            MAKE-CDXR FDEFINE-CAREFULLY SET-FUNCTION-PRETTY-ARGLIST
            DOCTOR-DFUN-FOR-THE-DEBUGGER DO-SATISFIES-DEFTYPE
            CANONICALIZE-SLOT-SPECIFICATION LOAD-DEFOPCODE
            CANONICALIZE-DEFCLASS-OPTION EARLY-SORT-METHODS
            LOAD-DEFOPERAND REAL-ADD-METHOD BOOTSTRAP-SLOT-INDEX
            |SETF PCL FIND-CLASS| CLASS-CAN-PRECEDE-P
            PROCLAIM-DEFGENERIC)) 
(PROCLAIM '(FTYPE (FUNCTION NIL FIXNUM) GET-WRAPPER-CACHE-NUMBER)) 
(IN-PACKAGE "PCL")

(DOLIST (V '(REMOVE-DIRECT-SUBCLASS |(BOUNDP NO-OF-INSTANCE-SLOTS)|
                CLASS-DIRECT-SUPERCLASSES CLASS-DIRECT-SUBCLASSES
                ADD-READER-METHOD
                SHORT-COMBINATION-IDENTITY-WITH-ONE-ARGUMENT
                |DEFINITION-SOURCE-MIXIN class predicate|
                REMOVE-READER-METHOD METHOD-FUNCTION EQL-SPECIALIZER-P
                |(SETF GENERIC-FUNCTION-NAME)| OBJECT-PLIST
                METHOD-LAMBDA-LIST
                SLOT-DEFINITION-DEFSTRUCT-ACCESSOR-SYMBOL
                SPECIALIZER-TYPE GF-DFUN-STATE
                |(SETF GENERIC-FUNCTION-METHOD-CLASS)|
                |(SETF GENERIC-FUNCTION-METHOD-COMBINATION)|
                CLASS-DEFAULT-INITARGS SLOT-DEFINITION-INITARGS
                CLASS-DEFSTRUCT-CONSTRUCTOR
                |(SETF GENERIC-FUNCTION-METHODS)| ADD-DIRECT-METHOD
                |(SETF GF-PRETTY-ARGLIST)| SPECIALIZERP
                EXACT-CLASS-SPECIALIZER-P
                |STANDARD-OBJECT class predicate|
                COMPATIBLE-META-CLASS-CHANGE-P
                ENSURE-GENERIC-FUNCTION-USING-CLASS
                |(BOUNDP READER-FUNCTION)| |(BOUNDP PREDICATE-NAME)|
                |(BOUNDP READERS)|
                |STANDARD-METHOD-COMBINATION class predicate|
                SPECIALIZER-DIRECT-METHODS UPDATE-GF-DFUN
                |(BOUNDP CLASS-PRECEDENCE-LIST)|
                |(BOUNDP ACCESSOR-FLAGS)|
                |STANDARD-EFFECTIVE-SLOT-DEFINITION class predicate|
                CONSTRUCTOR-SUPPLIED-INITARG-NAMES
                |(BOUNDP DOCUMENTATION)| |(BOUNDP LOCATION)|
                SPECIALIZER-OBJECT METHOD-SPECIALIZERS
                CLASS-FINALIZED-P
                |(BOUNDP INCOMPATIBLE-SUPERCLASS-LIST)|
                |(BOUNDP CODE-TYPE)| ACCESSOR-METHOD-SLOT-NAME
                |(BOUNDP SPECIALIZERS)|
                |(BOUNDP IDENTITY-WITH-ONE-ARGUMENT)|
                |STANDARD-DIRECT-SLOT-DEFINITION class predicate|
                |(BOUNDP CODE-GENERATORS)| SPECIALIZER-CLASS
                |(BOUNDP PRETTY-ARGLIST)| |(BOUNDP DEFSTRUCT-FORM)|
                |(SETF SLOT-DEFINITION-DEFSTRUCT-ACCESSOR-SYMBOL)|
                CLASS-EQ-SPECIALIZER-P ENSURE-CLASS-USING-CLASS
                SLOTS-FETCHER |(SETF SLOT-ACCESSOR-STD-P)|
                |STANDARD-SLOT-DEFINITION class predicate|
                REMOVE-WRITER-METHOD |(BOUNDP INITFUNCTION)|
                |(BOUNDP WRITER-FUNCTION)| STRUCTURE-CLASS-P
                |(BOUNDP WRITERS)| |(BOUNDP INITFORM)|
                GENERIC-FUNCTION-NAME |(BOUNDP FUNCTION-NAME)|
                UPDATE-CONSTRUCTORS ADD-DIRECT-SUBCLASS
                |(BOUNDP SLOT-NAME)| |(SETF SLOT-DEFINITION-INITARGS)|
                |(BOUNDP ALLOCATION)| DOCUMENTATION |(BOUNDP FUNCTION)|
                |(BOUNDP GENERIC-FUNCTION)|
                |SLOT-OBJECT class predicate| |(BOUNDP LAMBDA-LIST)|
                METHOD-PRETTY-ARGLIST |RATIONAL class predicate|
                |(BOUNDP CAN-PRECEDE-LIST)| |(BOUNDP PROTOTYPE)|
                CLASS-EQ-SPECIALIZER INFORM-TYPE-SYSTEM-ABOUT-CLASS
                |PCL-CLASS class predicate| |(BOUNDP DFUN-STATE)|
                |(BOUNDP FROM-DEFCLASS-P)| |(READER METHOD)|
                |(BOUNDP SUPPLIED-INITARG-NAMES)|
                CLASS-NO-OF-INSTANCE-SLOTS |(BOUNDP METHOD-CLASS)|
                |(READER SOURCE)| |(BOUNDP METHOD-COMBINATION)|
                |(BOUNDP INTERNAL-READER-FUNCTION)|
                |(BOUNDP INTERNAL-WRITER-FUNCTION)|
                |(BOUNDP DIRECT-METHODS)| |(BOUNDP DIRECT-SLOTS)|
                GENERIC-FUNCTION-METHOD-COMBINATION
                GENERIC-FUNCTION-METHODS |(BOUNDP BOUNDP-FUNCTION)|
                |(BOUNDP DIRECT-SUPERCLASSES)|
                |(BOUNDP DIRECT-SUBCLASSES)| ADD-DEPENDENT
                SLOT-VALUE-USING-CLASS |(BOUNDP OPTIONS)|
                |(BOUNDP METHODS)| CLASS-PROTOTYPE
                DIRECT-SLOT-DEFINITION-CLASS |(WRITER METHOD)|
                GENERIC-FUNCTION-METHOD-CLASS
                |(READER NO-OF-INSTANCE-SLOTS)|
                GENERIC-FUNCTION-LAMBDA-LIST
                GENERIC-FUNCTION-PRETTY-ARGLIST
                MAKE-CONSTRUCTOR-CODE-GENERATORS |(WRITER SOURCE)|
                MAKE-BOUNDP-METHOD-FUNCTION
                |SLOT-DEFINITION class predicate|
                |METAOBJECT class predicate| FINALIZE-INHERITANCE
                |(WRITER NO-OF-INSTANCE-SLOTS)| CLASS-PREDICATE-NAME
                |SEQUENCE class predicate| LOAD-CONSTRUCTOR-INTERNAL
                COMPUTE-EFFECTIVE-METHOD CLASSP
                |CHARACTER class predicate|
                |CONSTRUCTOR class predicate| |COMPLEX class predicate|
                |STD-CLASS class predicate| LEGAL-QUALIFIERS-P
                ADD-BOUNDP-METHOD LEGAL-LAMBDA-LIST-P
                SLOT-MAKUNBOUND-USING-CLASS
                |SETF PCL GENERIC-FUNCTION-NAME|
                |SETF PCL METHOD-FUNCTION-NAME|
                |DEPENDENT-UPDATE-MIXIN class predicate|
                |(READER READER-FUNCTION)| |(READER PREDICATE-NAME)|
                |(READER READERS)| DESCRIBE-OBJECT
                |(READER CLASS-PRECEDENCE-LIST)| CLASS-PRECEDENCE-LIST
                |(READER ACCESSOR-FLAGS)| |(READER DOCUMENTATION)|
                |(READER LOCATION)| |(SETF CLASS-SLOT-VALUE)|
                MAKE-WRITER-METHOD-FUNCTION |SETF PCL GF-DFUN-STATE|
                |(READER INCOMPATIBLE-SUPERCLASS-LIST)|
                |(READER CODE-TYPE)|
                |LONG-METHOD-COMBINATION class predicate|
                |(READER SPECIALIZERS)|
                |(READER IDENTITY-WITH-ONE-ARGUMENT)|
                COMPUTE-EFFECTIVE-SLOT-DEFINITION
                |VECTOR class predicate| SLOT-BOUNDP-USING-CLASS
                |(READER CODE-GENERATORS)|
                COMPUTE-CLASS-PRECEDENCE-LIST |(READER PRETTY-ARGLIST)|
                |(READER DEFSTRUCT-FORM)|
                |SETF PCL SLOT-DEFINITION-NAME| |SETF PCL CLASS-NAME|
                |(WRITER READER-FUNCTION)|
                |(SETF CLASS-DEFSTRUCT-CONSTRUCTOR)|
                |(METHOD CHANGE-CLASS (T SYMBOL))|
                |(WRITER PREDICATE-NAME)| |(WRITER READERS)|
                |(METHOD WRAPPER-FETCHER (FUNCALLABLE-STANDARD-CLASS))|
                |(METHOD UPDATE-INSTANCE-FOR-DIFFERENT-CLASS (STANDARD-OBJECT STANDARD-OBJECT))|
                |(METHOD WRAPPER-FETCHER (STANDARD-CLASS))|
                |(METHOD CLASS-FINALIZED-P (PCL-CLASS))|
                |(METHOD CLASS-PROTOTYPE (STD-CLASS))|
                |(METHOD CLASS-PROTOTYPE (STRUCTURE-CLASS))|
                |(METHOD CLASS-DIRECT-DEFAULT-INITARGS (SLOT-CLASS))|
                |(METHOD CLASS-DEFAULT-INITARGS (SLOT-CLASS))|
                |(METHOD CLASS-CONSTRUCTORS (SLOT-CLASS))|
                |(METHOD CLASS-SLOT-CELLS (STD-CLASS))|
                |(METHOD CHANGE-CLASS (STANDARD-OBJECT STANDARD-CLASS))|
                |(METHOD CHANGE-CLASS (STANDARD-OBJECT FUNCALLABLE-STANDARD-CLASS))|
                |(METHOD CLASS-DIRECT-SLOTS (BUILT-IN-CLASS))|
                |(METHOD CLASS-SLOTS (BUILT-IN-CLASS))|
                |(METHOD CLASS-DIRECT-DEFAULT-INITARGS (BUILT-IN-CLASS))|
                |(METHOD CLASS-DEFAULT-INITARGS (BUILT-IN-CLASS))|
                |(READER INITFUNCTION)| |(READER WRITER-FUNCTION)|
                |(METHOD DOCUMENTATION (DOCUMENTATION-MIXIN))|
                INITIALIZE-INTERNAL-SLOT-FUNCTIONS
                |SETF PCL SLOT-DEFINITION-TYPE|
                |(SETF METHOD-FUNCTION-NAME)| |(READER WRITERS)|
                |(WRITER CLASS-PRECEDENCE-LIST)|
                |(WRITER ACCESSOR-FLAGS)| |(READER INITFORM)|
                METHOD-COMBINATION-P
                |(METHOD SPECIALIZER-DIRECT-METHODS (SPECIALIZER-WITH-OBJECT))|
                |(METHOD SPECIALIZER-DIRECT-GENERIC-FUNCTIONS (SPECIALIZER-WITH-OBJECT))|
                |(WRITER DOCUMENTATION)| |(WRITER LOCATION)|
                |STRUCTURE-DIRECT-SLOT-DEFINITION class predicate|
                |(METHOD ACCESSOR-METHOD-SLOT-NAME (TRACED-METHOD))|
                |(METHOD DOCUMENTATION (STANDARD-SLOT-DEFINITION))|
                |(READER FUNCTION-NAME)|
                |(METHOD SPECIALIZER-CLASS (EQL-SPECIALIZER))|
                |(METHOD SPECIALIZER-METHOD-TABLE (EQL-SPECIALIZER))|
                |(METHOD SPECIALIZER-METHOD-TABLE (CLASS-EQ-SPECIALIZER))|
                |STRUCTURE-EFFECTIVE-SLOT-DEFINITION class predicate|
                |(METHOD (SETF DOCUMENTATION) (T DOCUMENTATION-MIXIN))|
                |SETF PCL GENERIC-FUNCTION-METHODS|
                |SETF PCL GENERIC-FUNCTION-METHOD-COMBINATION|
                |SETF PCL METHOD-GENERIC-FUNCTION|
                |(METHOD ADD-CONSTRUCTOR (SLOT-CLASS CONSTRUCTOR))|
                |(METHOD ADD-DIRECT-METHOD (CLASS METHOD))|
                |(METHOD ADD-DIRECT-METHOD (SPECIALIZER-WITH-OBJECT METHOD))|
                |(READER SLOT-NAME)|
                |(WRITER INCOMPATIBLE-SUPERCLASS-LIST)|
                |SETF PCL SLOT-ACCESSOR-STD-P| |(WRITER CODE-TYPE)|
                |(METHOD ADD-DIRECT-SUBCLASS (CLASS CLASS))|
                |(METHOD UPDATE-CONSTRUCTORS (SLOT-CLASS))|
                |(METHOD UPDATE-CONSTRUCTORS (CLASS))|
                |(READER ALLOCATION)|
                |(METHOD (SETF SLOT-VALUE-USING-CLASS) (T STD-CLASS STANDARD-OBJECT STANDARD-EFFECTIVE-SLOT-DEFINITION))|
                |(METHOD (SETF SLOT-VALUE-USING-CLASS) (T STRUCTURE-CLASS STRUCTURE-OBJECT STRUCTURE-EFFECTIVE-SLOT-DEFINITION))|
                |(METHOD (SETF SLOT-DEFINITION-LOCATION) :AFTER (T STANDARD-EFFECTIVE-SLOT-DEFINITION))|
                |(METHOD (SETF DOCUMENTATION) (T STANDARD-SLOT-DEFINITION))|
                |SETF PCL CONSTRUCTOR-CODE-TYPE|
                |(WRITER SPECIALIZERS)|
                |(WRITER IDENTITY-WITH-ONE-ARGUMENT)|
                |(METHOD SPECIALIZER-CLASS (CLASS))|
                |(METHOD SPECIALIZER-DIRECT-METHODS (CLASS))|
                |(METHOD SPECIALIZER-DIRECT-GENERIC-FUNCTIONS (CLASS))|
                |(SETF METHOD-GENERIC-FUNCTION)|
                |(WRITER CODE-GENERATORS)| |(WRITER PRETTY-ARGLIST)|
                LEGAL-SPECIALIZERS-P |SETF PCL OBJECT-PLIST|
                |(WRITER DEFSTRUCT-FORM)|
                |(METHOD INITIALIZE-INSTANCE (SLOT-OBJECT))|
                |(METHOD REINITIALIZE-INSTANCE (SLOT-OBJECT))|
                |(READER FUNCTION)| |(READER GENERIC-FUNCTION)|
                |(READER LAMBDA-LIST)| |SLOT-CLASS class predicate|
                |SETF PCL SLOT-DEFINITION-INITFORM|
                |SETF PCL CLASS-DEFSTRUCT-FORM|
                |(READER CAN-PRECEDE-LIST)|
                |SETF PCL GENERIC-FUNCTION-METHOD-CLASS|
                |(READER PROTOTYPE)| |(WRITER INITFUNCTION)|
                |(WRITER WRITER-FUNCTION)|
                |(METHOD REINITIALIZE-INSTANCE :AFTER (STANDARD-GENERIC-FUNCTION))|
                |(METHOD INITIALIZE-INSTANCE :AFTER (STANDARD-GENERIC-FUNCTION))|
                |(METHOD REINITIALIZE-INSTANCE (STANDARD-METHOD))|
                |(METHOD INITIALIZE-INTERNAL-SLOT-FUNCTIONS (EFFECTIVE-SLOT-DEFINITION))|
                |(WRITER WRITERS)| SLOT-ACCESSOR-STD-P
                |(WRITER INITFORM)|
                |(METHOD REINITIALIZE-INSTANCE :BEFORE (SLOT-CLASS))|
                |(METHOD REINITIALIZE-INSTANCE :AFTER (SLOT-CLASS))|
                |(READER DFUN-STATE)| |(WRITER FUNCTION-NAME)|
                |(READER FROM-DEFCLASS-P)| |SETF PCL GF-PRETTY-ARGLIST|
                |(READER SUPPLIED-INITARG-NAMES)|
                |SETF PCL SLOT-DEFINITION-LOCATION|
                |SETF PCL SLOT-DEFINITION-READER-FUNCTION|
                |SETF PCL SLOT-DEFINITION-WRITER-FUNCTION|
                |SETF PCL SLOT-DEFINITION-BOUNDP-FUNCTION|
                |SETF PCL SLOT-DEFINITION-INTERNAL-READER-FUNCTION|
                |SETF PCL SLOT-DEFINITION-INTERNAL-WRITER-FUNCTION|
                |SETF PCL SLOT-DEFINITION-ALLOCATION|
                |SETF PCL SLOT-DEFINITION-INITFUNCTION|
                |SETF PCL SLOT-ACCESSOR-FUNCTION|
                |(METHOD MAKE-INSTANCE (SYMBOL))|
                |(METHOD MAKE-INSTANCES-OBSOLETE (SYMBOL))|
                |(WRITER SLOT-NAME)| |(BOUNDP NAME)|
                |(METHOD SAME-SPECIALIZER-P (EQL-SPECIALIZER EQL-SPECIALIZER))|
                |(METHOD SAME-SPECIALIZER-P (CLASS-EQ-SPECIALIZER CLASS-EQ-SPECIALIZER))|
                |(METHOD SAME-SPECIALIZER-P (SPECIALIZER SPECIALIZER))|
                COMPUTE-DISCRIMINATING-FUNCTION
                |(METHOD MAKE-INSTANCE (SLOT-CLASS))|
                |(METHOD MAKE-INSTANCES-OBSOLETE (STD-CLASS))|
                |(WRITER ALLOCATION)| |(READER METHOD-CLASS)|
                |(METHOD SLOTS-TO-INSPECT (SLOT-CLASS SLOT-OBJECT))|
                |(METHOD ALLOCATE-INSTANCE (FUNCALLABLE-STANDARD-CLASS))|
                |(METHOD VALIDATE-SUPERCLASS (FUNCALLABLE-STANDARD-CLASS STANDARD-CLASS))|
                |(SETF OBJECT-PLIST)|
                |(METHOD ALLOCATE-INSTANCE (STANDARD-CLASS))|
                |(METHOD ALLOCATE-INSTANCE (STRUCTURE-CLASS))|
                |(METHOD VALIDATE-SUPERCLASS (CLASS CLASS))|
                |(METHOD VALIDATE-SUPERCLASS (CLASS BUILT-IN-CLASS))|
                |(METHOD VALIDATE-SUPERCLASS (SLOT-CLASS FORWARD-REFERENCED-CLASS))|
                |(READER METHOD-COMBINATION)|
                |(READER INTERNAL-READER-FUNCTION)|
                |(READER INTERNAL-WRITER-FUNCTION)|
                METHOD-COMBINATION-OPTIONS
                |(METHOD COMPUTE-CONSTRUCTOR-CODE (SLOT-CLASS CONSTRUCTOR))|
                |(METHOD REMOVE-CONSTRUCTOR (SLOT-CLASS CONSTRUCTOR))|
                |(METHOD COMPUTE-DISCRIMINATING-FUNCTION (STANDARD-GENERIC-FUNCTION))|
                |(METHOD COMPUTE-DISCRIMINATING-FUNCTION-ARGLIST-INFO (STANDARD-GENERIC-FUNCTION))|
                |(METHOD REMOVE-DIRECT-METHOD (CLASS METHOD))|
                |(METHOD REMOVE-DIRECT-METHOD (SPECIALIZER-WITH-OBJECT METHOD))|
                |(READER DIRECT-METHODS)| |(READER DIRECT-SLOTS)|
                |SETF PCL SLOT-DEFINITION-READERS|
                |(METHOD SAME-SPECIALIZER-P (CLASS CLASS))|
                |(METHOD REMOVE-DIRECT-SUBCLASS (CLASS CLASS))|
                |(METHOD COMPUTE-DEFAULT-INITARGS (SLOT-CLASS))|
                |(METHOD COMPUTE-SLOTS (STD-CLASS))|
                |(METHOD COMPUTE-SLOTS :AROUND (STD-CLASS))|
                |(METHOD COMPUTE-SLOTS (STRUCTURE-CLASS))|
                |(METHOD COMPUTE-SLOTS :AROUND (STRUCTURE-CLASS))|
                |(METHOD COMPUTE-CLASS-PRECEDENCE-LIST (SLOT-CLASS))|
                |(WRITER FUNCTION)| |(WRITER GENERIC-FUNCTION)|
                |STRUCTURE-OBJECT class predicate|
                |(READER BOUNDP-FUNCTION)| |SETF PCL DOCUMENTATION|
                |(READER DIRECT-SUPERCLASSES)|
                |(READER DIRECT-SUBCLASSES)|
                |(METHOD GENERIC-FUNCTION-PRETTY-ARGLIST (STANDARD-GENERIC-FUNCTION))|
                |(METHOD FUNCTION-KEYWORDS (STANDARD-METHOD))|
                |(METHOD GENERIC-FUNCTION-LAMBDA-LIST (GENERIC-FUNCTION))|
                |(SETF GF-VALID-P)| |(WRITER LAMBDA-LIST)|
                FUNCALLABLE-STANDARD-CLASS-P |(BOUNDP CLASS)|
                |(METHOD FINALIZE-INHERITANCE (STRUCTURE-CLASS))|
                |(METHOD FINALIZE-INHERITANCE (STD-CLASS))|
                |(METHOD SLOT-VALUE-USING-CLASS (STD-CLASS STANDARD-OBJECT STANDARD-EFFECTIVE-SLOT-DEFINITION))|
                |(METHOD SLOT-BOUNDP-USING-CLASS (STD-CLASS STANDARD-OBJECT STANDARD-EFFECTIVE-SLOT-DEFINITION))|
                |(METHOD SLOT-MAKUNBOUND-USING-CLASS (STD-CLASS STANDARD-OBJECT STANDARD-EFFECTIVE-SLOT-DEFINITION))|
                |(METHOD SLOT-EXISTS-P-USING-CLASS (STD-CLASS STANDARD-OBJECT STANDARD-EFFECTIVE-SLOT-DEFINITION))|
                |(METHOD SLOT-VALUE-USING-CLASS (STRUCTURE-CLASS STRUCTURE-OBJECT STRUCTURE-EFFECTIVE-SLOT-DEFINITION))|
                |(METHOD SLOT-BOUNDP-USING-CLASS (STRUCTURE-CLASS STRUCTURE-OBJECT STRUCTURE-EFFECTIVE-SLOT-DEFINITION))|
                |(METHOD SLOT-MAKUNBOUND-USING-CLASS (STRUCTURE-CLASS STRUCTURE-OBJECT STRUCTURE-EFFECTIVE-SLOT-DEFINITION))|
                |(METHOD SLOT-DEFINITION-ALLOCATION (STRUCTURE-SLOT-DEFINITION))|
                |(READER OPTIONS)| |(READER METHODS)|
                |(WRITER CAN-PRECEDE-LIST)|
                |SETF PCL SLOT-DEFINITION-CLASS|
                |SETF PCL SLOT-VALUE-USING-CLASS| |(WRITER PROTOTYPE)|
                |(BOUNDP TYPE)| |(BOUNDP OBJECT)|
                CLASS-CAN-PRECEDE-LIST
                |SETF PCL CLASS-NO-OF-INSTANCE-SLOTS|
                |SETF PCL CLASS-DIRECT-SLOTS| |SETF PCL CLASS-SLOTS|
                |(METHOD SLOTS-FETCHER (FUNCALLABLE-STANDARD-CLASS))|
                |(METHOD SLOTS-FETCHER (STANDARD-CLASS))|
                SLOT-ACCESSOR-FUNCTION |(BOUNDP PLIST)|
                |SETF PCL CLASS-INCOMPATIBLE-SUPERCLASS-LIST|
                |SETF PCL SLOT-DEFINITION-WRITERS|
                |(WRITER DFUN-STATE)| |(WRITER FROM-DEFCLASS-P)|
                |(BOUNDP SLOTS)| |(WRITER SUPPLIED-INITARG-NAMES)|
                |STRUCTURE-SLOT-DEFINITION class predicate|
                MAKE-READER-METHOD-FUNCTION |STRING class predicate|
                LEGAL-METHOD-FUNCTION-P CLASS-SLOTS
                |(METHOD INSTALL-LAZY-CONSTRUCTOR-INSTALLER (CONSTRUCTOR))|
                |NUMBER class predicate| |(WRITER METHOD-CLASS)|
                |(METHOD ENSURE-CLASS-USING-CLASS (T PCL-CLASS))|
                |(WRITER METHOD-COMBINATION)| GET-METHOD
                |(WRITER INTERNAL-READER-FUNCTION)|
                |(WRITER INTERNAL-WRITER-FUNCTION)|
                |(METHOD METHOD-QUALIFIERS (TRACED-METHOD))|
                |(METHOD METHOD-SPECIALIZERS (TRACED-METHOD))|
                |(METHOD METHOD-LAMBDA-LIST (TRACED-METHOD))|
                |(METHOD METHOD-PRETTY-ARGLIST (STANDARD-METHOD))|
                |(METHOD METHOD-QUALIFIERS (STANDARD-METHOD))|
                |(METHOD METHOD-FUNCTION-FOR-CACHING-P (STANDARD-ACCESSOR-METHOD))|
                |(METHOD METHOD-FUNCTION-FOR-CACHING-P (STANDARD-METHOD))|
                |(WRITER DIRECT-METHODS)| |(WRITER DIRECT-SLOTS)|
                SLOT-DEFINITION-NAME VALIDATE-SUPERCLASS
                |(WRITER BOUNDP-FUNCTION)|
                |(WRITER DIRECT-SUPERCLASSES)|
                |(WRITER DIRECT-SUBCLASSES)| |(WRITER OPTIONS)|
                |(WRITER METHODS)| SLOT-DEFINITION-TYPE
                SHORT-METHOD-COMBINATION-P GF-ARG-INFO
                CLASS-DIRECT-SLOTS
                |(METHOD RAW-INSTANCE-ALLOCATOR (FUNCALLABLE-STANDARD-CLASS))|
                |(METHOD RAW-INSTANCE-ALLOCATOR (STANDARD-CLASS))|
                |SYMBOL class predicate| SPECIALIZER-METHOD-TABLE
                |(METHOD MAYBE-UPDATE-CONSTRUCTORS (GENERIC-FUNCTION METHOD))|
                CLASS-DEFSTRUCT-FORM METHOD-CLOSURE-GENERATOR
                REMOVE-CONSTRUCTOR SLOT-DEFINITION-INITFORM
                GF-PRETTY-ARGLIST SAME-SPECIALIZER-P CONSTRUCTOR-NAME
                SLOT-DEFINITION-LOCATION
                SLOT-DEFINITION-BOUNDP-FUNCTION
                SLOT-DEFINITION-WRITER-FUNCTION
                SLOT-DEFINITION-READER-FUNCTION
                SLOT-DEFINITION-INTERNAL-WRITER-FUNCTION
                SLOT-DEFINITION-INTERNAL-READER-FUNCTION
                SLOT-DEFINITION-ALLOCATION SLOT-DEFINITION-INITFUNCTION
                CONSTRUCTOR-CODE-TYPE SLOT-DEFINITION-READERS
                ADD-CONSTRUCTOR SLOT-DEFINITION-CLASS GET-CONSTRUCTOR
                EQL-SPECIALIZER-OBJECT SLOT-DEFINITION-WRITERS
                |RATIO class predicate| CLASS-CONSTRUCTORS
                |(BOUNDP WRAPPER)| SLOTS-TO-INSPECT
                FIND-METHOD-COMBINATION
                |(BOUNDP DEFSTRUCT-ACCESSOR-SYMBOL)|
                SPECIALIZER-DIRECT-GENERIC-FUNCTIONS
                |(BOUNDP CLASS-EQ-SPECIALIZER)|
                |(SETF SLOT-DEFINITION-NAME)| ADD-WRITER-METHOD
                COMPUTE-SLOTS |(BOUNDP OPERATOR)| |(BOUNDP ARG-INFO)|
                CONSTRUCTOR-CLASS |(SETF SLOT-DEFINITION-CLASS)|
                |(SETF SLOT-VALUE-USING-CLASS)|
                |(SETF SLOT-DEFINITION-ALLOCATION)|
                |(SETF SLOT-DEFINITION-BOUNDP-FUNCTION)|
                |(SETF SLOT-DEFINITION-INITFUNCTION)|
                |(SETF SLOT-DEFINITION-INTERNAL-READER-FUNCTION)|
                |(SETF SLOT-DEFINITION-INTERNAL-WRITER-FUNCTION)|
                |(SETF SLOT-DEFINITION-LOCATION)|
                |(SETF SLOT-DEFINITION-READER-FUNCTION)|
                |(SETF SLOT-DEFINITION-WRITER-FUNCTION)|
                |(SETF SLOT-ACCESSOR-FUNCTION)|
                |(BOUNDP DEFSTRUCT-CONSTRUCTOR)|
                |(SETF SLOT-DEFINITION-READERS)|
                |(SETF SLOT-DEFINITION-WRITERS)|
                MAYBE-UPDATE-CONSTRUCTORS |(SETF SLOT-DEFINITION-TYPE)|
                CONSTRUCTOR-CODE-GENERATORS
                |(SETF SLOT-DEFINITION-INITFORM)|
                |EFFECTIVE-SLOT-DEFINITION class predicate|
                |LIST class predicate| |(BOUNDP VALID-P)|
                |(BOUNDP INITARGS)| LONG-METHOD-COMBINATION-FUNCTION
                |BUILT-IN-CLASS class predicate| GENERIC-FUNCTION-P
                |T class predicate| |FLOAT class predicate|
                |(READER NAME)| |(BOUNDP CLOSURE-GENERATOR)|
                MAP-DEPENDENTS |CONS class predicate| |(READER CLASS)|
                LEGAL-SLOT-NAME-P |(READER TYPE)| |(READER OBJECT)|
                CLASS-WRAPPER |(READER PLIST)| GF-VALID-P
                |(METHOD NO-APPLICABLE-METHOD (T))| |(READER SLOTS)|
                |ARRAY class predicate| |(WRITER NAME)|
                DEFINITION-SOURCE DEFAULT-INITARGS
                |NULL class predicate| |(WRITER CLASS)|
                CLASS-SLOT-VALUE |(WRITER TYPE)| |(WRITER OBJECT)|
                |(WRITER PLIST)| |(WRITER SLOTS)|
                FORWARD-REFERENCED-CLASS-P
                |SPECIALIZER-WITH-OBJECT class predicate|
                LEGAL-QUALIFIER-P METHOD-P
                |PLIST-MIXIN class predicate| CLASS-SLOT-CELLS
                COMPUTE-CONSTRUCTOR-CODE
                |(METHOD LOAD-CONSTRUCTOR-INTERNAL (SLOT-CLASS T T T))|
                |(METHOD SHARED-INITIALIZE :BEFORE (STANDARD-GENERIC-FUNCTION T))|
                |(METHOD SHARED-INITIALIZE :AFTER (STANDARD-METHOD T))|
                |(METHOD SHARED-INITIALIZE :BEFORE (STANDARD-ACCESSOR-METHOD T))|
                |(METHOD SHARED-INITIALIZE :BEFORE (STANDARD-METHOD T))|
                |(METHOD SHARED-INITIALIZE :AFTER (STRUCTURE-SLOT-DEFINITION T))|
                |(METHOD SHARED-INITIALIZE :AFTER (STANDARD-SLOT-DEFINITION T))|
                |(METHOD CLASS-SLOT-VALUE (STD-CLASS T))|
                |(METHOD SHARED-INITIALIZE (SLOT-OBJECT T))|
                |(METHOD SHARED-INITIALIZE :AFTER (DOCUMENTATION-MIXIN T))|
                |(METHOD SHARED-INITIALIZE :AFTER (CLASS-EQ-SPECIALIZER T))|
                |(METHOD SHARED-INITIALIZE :AFTER (EQL-SPECIALIZER T))|
                |(METHOD SHARED-INITIALIZE :AFTER (STD-CLASS T))|
                |(METHOD SHARED-INITIALIZE :BEFORE (CLASS T))|
                |(METHOD SHARED-INITIALIZE :AFTER (STRUCTURE-CLASS T))|
                |(METHOD SHARED-INITIALIZE :BEFORE (BUILT-IN-CLASS T))|
                STANDARD-ACCESSOR-METHOD-P |(SETF CLASS-NAME)|
                |(METHOD UPDATE-GF-DFUN (STD-CLASS T))|
                |(METHOD UPDATE-INSTANCE-FOR-REDEFINED-CLASS (STANDARD-OBJECT T T T))|
                |(METHOD ADD-READER-METHOD (SLOT-CLASS T T))|
                |(METHOD ADD-WRITER-METHOD (SLOT-CLASS T T))|
                |(METHOD ADD-BOUNDP-METHOD (SLOT-CLASS T T))|
                |(METHOD ADD-DEPENDENT (DEPENDENT-UPDATE-MIXIN T))|
                STANDARD-GENERIC-FUNCTION-P STANDARD-METHOD-P
                STANDARD-READER-METHOD-P |(METHOD DOCUMENTATION (T))|
                |(READER WRAPPER)|
                |(METHOD (SETF CLASS-SLOT-VALUE) (T STD-CLASS T))|
                |(METHOD (SETF SLOT-ACCESSOR-FUNCTION) (T EFFECTIVE-SLOT-DEFINITION T))|
                |(METHOD (SETF SLOT-ACCESSOR-STD-P) (T EFFECTIVE-SLOT-DEFINITION T))|
                |(METHOD (SETF DOCUMENTATION) (T T))|
                |SETF PCL GF-VALID-P| |TRACED-METHOD class predicate|
                SLOT-EXISTS-P-USING-CLASS
                |(READER DEFSTRUCT-ACCESSOR-SYMBOL)|
                |(METHOD INFORM-TYPE-SYSTEM-ABOUT-CLASS (STRUCTURE-CLASS T))|
                |(METHOD DEFAULT-INITARGS (SLOT-CLASS T))|
                |(METHOD EFFECTIVE-SLOT-DEFINITION-CLASS (STD-CLASS T))|
                |(METHOD EFFECTIVE-SLOT-DEFINITION-CLASS (STRUCTURE-CLASS T))|
                |(METHOD INFORM-TYPE-SYSTEM-ABOUT-CLASS (STD-CLASS T))|
                |(READER CLASS-EQ-SPECIALIZER)|
                COMPUTE-DEFAULT-INITARGS
                COMPUTE-EFFECTIVE-SLOT-DEFINITION-INITARGS
                |(METHOD LEGAL-SPECIALIZER-P (STANDARD-METHOD T))|
                |(METHOD LEGAL-SPECIALIZERS-P (STANDARD-METHOD T))|
                |(METHOD LEGAL-SLOT-NAME-P (STANDARD-METHOD T))|
                |(METHOD LEGAL-QUALIFIER-P (STANDARD-METHOD T))|
                |(METHOD LEGAL-QUALIFIERS-P (STANDARD-METHOD T))|
                |(METHOD LEGAL-METHOD-FUNCTION-P (STANDARD-METHOD T))|
                |(METHOD LEGAL-LAMBDA-LIST-P (STANDARD-METHOD T))|
                |(METHOD LEGAL-DOCUMENTATION-P (STANDARD-METHOD T))|
                |(SETF CLASS-DEFSTRUCT-FORM)|
                |(SETF CLASS-INCOMPATIBLE-SUPERCLASS-LIST)|
                |SETF PCL CLASS-SLOT-VALUE|
                |(METHOD PRINT-OBJECT (CONSTRUCTOR T))|
                |(METHOD PRINT-OBJECT (METHOD-COMBINATION T))|
                |(METHOD PRINT-OBJECT (GENERIC-FUNCTION T))|
                |(METHOD PRINT-OBJECT (STANDARD-ACCESSOR-METHOD T))|
                |(METHOD PRINT-OBJECT (STANDARD-METHOD T))|
                |(METHOD PRINT-OBJECT (SLOT-DEFINITION T))|
                |(METHOD PRINT-OBJECT (CLASS T))|
                |(METHOD PRINT-OBJECT (T T))|
                |(SETF CLASS-DIRECT-SLOTS)|
                |(SETF CLASS-NO-OF-INSTANCE-SLOTS)|
                |(SETF CLASS-SLOTS)| |(READER OPERATOR)|
                |(READER ARG-INFO)| METHOD-COMBINATION-TYPE
                |(READER DEFSTRUCT-CONSTRUCTOR)|
                |(METHOD MAKE-CONSTRUCTOR-CODE-GENERATORS (SLOT-CLASS T T T T))|
                |(METHOD MAKE-WRITER-METHOD-FUNCTION (FUNCALLABLE-STANDARD-CLASS T))|
                |(METHOD MAKE-READER-METHOD-FUNCTION (FUNCALLABLE-STANDARD-CLASS T))|
                |(METHOD MAKE-READER-METHOD-FUNCTION (SLOT-CLASS T))|
                |(METHOD MAKE-WRITER-METHOD-FUNCTION (SLOT-CLASS T))|
                |(METHOD MAKE-BOUNDP-METHOD-FUNCTION (SLOT-CLASS T))|
                |(WRITER WRAPPER)| STANDARD-CLASS-P
                |(SETF CONSTRUCTOR-CODE-TYPE)| LEGAL-SPECIALIZER-P
                |(WRITER DEFSTRUCT-ACCESSOR-SYMBOL)|
                |(METHOD COMPUTE-EFFECTIVE-METHOD (GENERIC-FUNCTION LONG-METHOD-COMBINATION T))|
                |(METHOD COMPUTE-EFFECTIVE-METHOD (GENERIC-FUNCTION SHORT-METHOD-COMBINATION T))|
                |(METHOD COMPUTE-EFFECTIVE-METHOD (GENERIC-FUNCTION STANDARD-METHOD-COMBINATION T))|
                |(METHOD COMPUTE-APPLICABLE-METHODS-USING-CLASSES (GENERIC-FUNCTION T))|
                |(METHOD COMPUTE-APPLICABLE-METHODS (GENERIC-FUNCTION T))|
                |(METHOD REMOVE-NAMED-METHOD (T T))|
                |(METHOD COMPUTE-EFFECTIVE-SLOT-DEFINITION (SLOT-CLASS T))|
                |(METHOD COMPUTE-EFFECTIVE-SLOT-DEFINITION-INITARGS (SLOT-CLASS T))|
                |(METHOD COMPUTE-EFFECTIVE-SLOT-DEFINITION-INITARGS :AROUND (STRUCTURE-CLASS T))|
                |(METHOD REMOVE-READER-METHOD (SLOT-CLASS T))|
                |(METHOD REMOVE-WRITER-METHOD (SLOT-CLASS T))|
                |(METHOD REMOVE-BOUNDP-METHOD (SLOT-CLASS T))|
                |(METHOD COMPATIBLE-META-CLASS-CHANGE-P (T T))|
                |(METHOD REMOVE-DEPENDENT (DEPENDENT-UPDATE-MIXIN T))|
                |(READER VALID-P)|
                |DIRECT-SLOT-DEFINITION class predicate|
                METHOD-FUNCTION-NAME |(READER INITARGS)|
                REMOVE-DIRECT-METHOD |(WRITER CLASS-EQ-SPECIALIZER)|
                |(METHOD FIND-METHOD-COMBINATION (GENERIC-FUNCTION (EQL STANDARD) T))|
                STANDARD-BOUNDP-METHOD-P METHOD-FUNCTION-FOR-CACHING
                |(METHOD SLOT-MISSING (T T T T))|
                |(METHOD SLOT-UNBOUND (T T T))|
                |(METHOD SLOT-ACCESSOR-FUNCTION (EFFECTIVE-SLOT-DEFINITION T))|
                |(METHOD SLOT-ACCESSOR-STD-P (EFFECTIVE-SLOT-DEFINITION T))|
                |(SETF DOCUMENTATION)| RAW-INSTANCE-ALLOCATOR
                INSTALL-LAZY-CONSTRUCTOR-INSTALLER
                |(METHOD MAP-DEPENDENTS (DEPENDENT-UPDATE-MIXIN T))|
                METHOD-FUNCTION-FOR-CACHING-P
                |SETF PCL SLOT-DEFINITION-DEFSTRUCT-ACCESSOR-SYMBOL|
                |(WRITER OPERATOR)| |(WRITER ARG-INFO)|
                COMPUTE-DISCRIMINATING-FUNCTION-ARGLIST-INFO
                ALLOCATE-INSTANCE STANDARD-WRITER-METHOD-P
                CLASS-INCOMPATIBLE-SUPERCLASS-LIST
                |(WRITER DEFSTRUCT-CONSTRUCTOR)|
                |(METHOD DIRECT-SLOT-DEFINITION-CLASS (STRUCTURE-CLASS T))|
                |(METHOD DIRECT-SLOT-DEFINITION-CLASS (STD-CLASS T))|
                WRAPPER-FETCHER |INTEGER class predicate|
                METHOD-COMBINATION-DOCUMENTATION
                |(METHOD DESCRIBE-OBJECT (CLASS T))|
                |(METHOD DESCRIBE-OBJECT (STANDARD-GENERIC-FUNCTION T))|
                |(METHOD DESCRIBE-OBJECT (SLOT-OBJECT T))|
                |(METHOD DESCRIBE-OBJECT (T T))|
                |(METHOD DESCRIBE-OBJECT (CONSTRUCTOR T))|
                |SETF PCL SLOT-DEFINITION-INITARGS|
                |(READER CLOSURE-GENERATOR)|
                COMPUTE-APPLICABLE-METHODS-USING-CLASSES
                REMOVE-BOUNDP-METHOD
                |(METHOD GET-CONSTRUCTOR (SLOT-CLASS T))|
                |(METHOD METHOD-FUNCTION-FOR-CACHING (STANDARD-ACCESSOR-METHOD T))|
                |(METHOD METHOD-FUNCTION-FOR-CACHING (STANDARD-METHOD T))|
                |(WRITER VALID-P)|
                |SETF PCL CLASS-DEFSTRUCT-CONSTRUCTOR|
                |(WRITER INITARGS)| |(BOUNDP METHOD)| |(BOUNDP SOURCE)|
                |DOCUMENTATION-MIXIN class predicate|
                |(SETF GF-DFUN-STATE)| EFFECTIVE-SLOT-DEFINITION-CLASS
                SHORT-COMBINATION-OPERATOR |BIT-VECTOR class predicate|
                REMOVE-DEPENDENT |(WRITER CLOSURE-GENERATOR)|
                CLASS-DIRECT-DEFAULT-INITARGS REMOVE-NAMED-METHOD
                |(METHOD ENSURE-CLASS-USING-CLASS (T NULL))|
                METHOD-GENERIC-FUNCTION LEGAL-DOCUMENTATION-P
                COMPUTE-APPLICABLE-METHODS CLASS-NAME REMOVE-METHOD
                UPDATE-INSTANCE-FOR-REDEFINED-CLASS
                UPDATE-INSTANCE-FOR-DIFFERENT-CLASS CHANGE-CLASS
                SHARED-INITIALIZE ADD-METHOD SLOT-UNBOUND
                INITIALIZE-INSTANCE FUNCTION-KEYWORDS
                REINITIALIZE-INSTANCE MAKE-INSTANCE PRINT-OBJECT
                METHOD-QUALIFIERS MAKE-INSTANCES-OBSOLETE SLOT-MISSING
                NO-APPLICABLE-METHOD))
  (SETF (GET V 'COMPILER::PROCLAIMED-CLOSURE) T)) 
