;; Bootstrap file for the ef-octet-count changes.  Just need to change
;; the value of +ef-max+

(in-package "STREAM")

(handler-bind
    ((error (lambda (c)
	      (declare (ignore c))
	      (invoke-restart 'continue))))
  (defconstant +ef-max+ 14))

;; Unintern all the symbols in the UNIX package that conflict with the
;; symbols in the UNIX-ERRNO package.
(in-package "UNIX")
#+nil
(ext:without-package-locks 
  (dolist (s '(UNIX:ENOENT UNIX:EINPROGRESS UNIX:EBADF UNIX:EXDEV UNIX:EADDRINUSE
	       UNIX:EBADE UNIX:EIDRM UNIX:ENOTEMPTY UNIX:EISDIR UNIX:ESTRPIPE UNIX:EPERM
	       UNIX:ENOTCONN UNIX:EREMOTEIO UNIX:ESUCCESS UNIX:ETOOMANYREFS
	       UNIX:EPROTONOSUPPORT UNIX:EEXIST UNIX:ENOSR UNIX:EBADR UNIX:EHOSTUNREACH
	       UNIX:EADDRNOTAVAIL UNIX:ENOTDIR UNIX:ENETRESET UNIX:ENFILE UNIX:EALREADY
	       UNIX:EDEADLOCK UNIX:ELIBSCN UNIX:ESTALE UNIX:EISNAM UNIX:ETXTBSY UNIX:ENOSTR
	       UNIX:ETIME UNIX:ECHILD UNIX:EUCLEAN UNIX:EBADMSG UNIX:EINVAL UNIX:EFBIG
	       UNIX:EIO UNIX:EAFNOSUPPORT UNIX:ELIBBAD UNIX:EILSEQ UNIX:ECONNREFUSED
	       UNIX:EBUSY UNIX:ECONNRESET UNIX:ENOTUNIQ UNIX:E2BIG UNIX:EL2HLT
	       UNIX:EDESTADDRREQ UNIX:ENETUNREACH UNIX:EUSERS UNIX:ENOPKG UNIX:EFAULT
	       UNIX:ENODEV UNIX:ERANGE UNIX:EROFS UNIX:EPROTO UNIX:ENONET UNIX:ESRMNT
	       UNIX:ENOMSG UNIX:EPROTOTYPE UNIX:EREMOTE UNIX:ESPIPE UNIX:EL3RST
	       UNIX:ENOLINK UNIX:EREMCHG UNIX:ERESTART UNIX:ESRCH UNIX:ELIBMAX UNIX:ENOSYS
	       UNIX:ECOMM UNIX:ECONNABORTED UNIX:ENXIO UNIX:ELIBEXEC UNIX:EMLINK
	       UNIX:ENAMETOOLONG UNIX:ELNRNG UNIX:EMULTIHOP UNIX:ENOLCK UNIX:EDOM
	       UNIX:EAGAIN UNIX:EDOTDOT UNIX:EL2NSYNC UNIX:EADV UNIX:ENOEXEC UNIX:ELIBACC
	       UNIX:ENOTBLK UNIX:EDEADLK UNIX:ENOBUFS UNIX:ECHRNG UNIX:EDQUOT UNIX:EBADFD
	       UNIX:EPIPE UNIX:EMSGSIZE UNIX:ENETDOWN UNIX:EWOULDBLOCK UNIX:ESHUTDOWN
	       UNIX:EOPNOTSUPP UNIX:EL3HLT UNIX:EINTR UNIX:ENOTTY UNIX:ENOPROTOOPT
	       UNIX:EPFNOSUPPORT UNIX:ENOSPC UNIX:EBFONT UNIX:EISCONN UNIX:EMFILE
	       UNIX:ESOCKTNOSUPPORT UNIX:EHOSTDOWN UNIX:EACCES UNIX:ENOTSOCK UNIX:EBADRQC
	       UNIX:ELOOP UNIX:ETIMEDOUT UNIX:ENAVAIL UNIX:EBADSLT UNIX:ENOANO UNIX:ENOMEM))
    (unintern s "UNIX")))
