/* $Header: /Volumes/share2/src/cmucl/cvs2git/cvsroot/src/ldb/Attic/Makefile.orig,v 1.19 1991/03/14 22:01:13 wlott Exp $ */
INCLS = -I.

OBJS = ldb.o egets.o coreparse.o alloc.o monitor.o print.o \
	os.o vars.o assem.o parse.o interrupt.o test.o \
	search.o validate.o gc.o globals.o dynbind.o breakpoint.o \
	regnames.o backtrace.o bitbash.o save.o purify.o socket.o

#ifdef mips
CFLAGS = -O ${INCLS}
UNDEFSYMPATTERN=&
ASSEMFILE='mips-assem.s'
#endif
#ifdef ibmrt
CFLAGS = -g ${INCLS}
UNDEFSYMPATTERN=_&
ASSEMFILE='rt-assem.s'
#endif
#ifdef sparc
CFLAGS = -g ${INCLS}
UNDEFSYMPATTERN=_&
ASSEMFILE='sparc-assem.s'
#endif

all: ldb.map

ldb.map: ldb
	echo -n 'Map file for ldb version ' > ldb.map
	cat version >> ldb.map
	nm -gp ldb >> ldb.map


ldb: ${OBJS} version undefineds
	echo -n '1 + ' | cat - version | bc > ,version
	mv ,version version
	cc ${CFLAGS} -DVERSION=`cat version` -c version.c
	cc `cat undefineds` -o ,ldb ${OBJS} version.o -lmach -lm -lc
	mv -f ,ldb ldb

version:
	echo 0 > version

undefineds: undefineds.src
	/lib/cpp undefineds.src | \
	sed -e '/^#/d' -e '/^[ 	]*$$/d' -e 's/.*/-u ${UNDEFSYMPATTERN}/' | \
	sort -u > ,undefineds
	mv ,undefineds undefineds

assem.s:
	ln -s ${ASSEMFILE} assem.s


#ifdef mips

/* MIPS specific stuff. */

/* If we get an interrupt while in lisp code, the global pointer */
/* is trash.  Therefore, we can't use the GP relative addressing */
/* mode in the interrupt handlers. */

interrupt.o: interrupt.c
	cc ${CFLAGS} -G 0 -c interrupt.c

assem.o: assem.s lisp.h lispregs.h globals.h
	as -G 0 -o $@ assem.s

#endif

#ifdef ibmrt

assem.o: assem.s
	/lib/cpp assem.s | as -o assem.o

#endif


#ifdef sparc

assem.o: assem.s lisp.h lispregs.h globals.h
	as -P -o $@ assem.s

#endif


socket.o: socket.c
	cc ${CFLAGS} -DUNIXCONN -c socket.c

lisp.h:
	@echo "You must run genesis to create lisp.h!"
	@false

depend: depends

depends:
	rm -f Makefile.orig.BAK
	ln Makefile.orig Makefile.orig.BAK
	sed -n '1,/^\/\*@/p' Makefile.orig > Makefile.orig.NEW
	cc -M ${INCLS} *.c | egrep -v ' /usr/' >> Makefile.orig.NEW
	mv Makefile.orig.NEW Makefile.orig
	rm Makefile.orig.BAK

/*@ Do not edit anything after this line. */
alloc.o: alloc.c
alloc.o: lisp.h
alloc.o: ldb.h
alloc.o: alloc.h
alloc.o: globals.h
alloc.o: lisp.h
backtrace.o: backtrace.c
backtrace.o: ./signal.h
backtrace.o: ldb.h
backtrace.o: lisp.h
backtrace.o: globals.h
backtrace.o: lisp.h
backtrace.o: interrupt.h
backtrace.o: ./signal.h
backtrace.o: lispregs.h
bitbash.o: bitbash.c
breakpoint.o: breakpoint.c
breakpoint.o: ./signal.h
breakpoint.o: lisp.h
breakpoint.o: os.h
breakpoint.o: ldb.h
breakpoint.o: lispregs.h
breakpoint.o: globals.h
breakpoint.o: lisp.h
coreparse.o: coreparse.c
coreparse.o: lisp.h
coreparse.o: globals.h
coreparse.o: lisp.h
coreparse.o: core.h
coreparse.o: ldb.h
dynbind.o: dynbind.c
dynbind.o: ldb.h
dynbind.o: lisp.h
dynbind.o: globals.h
dynbind.o: lisp.h
egets.o: egets.c
egets.o: ./signal.h
gc.o: gc.c
gc.o: ./signal.h
gc.o: lisp.h
gc.o: ldb.h
gc.o: os.h
gc.o: ldb.h
gc.o: gc.h
gc.o: lisp.h
gc.o: globals.h
gc.o: lisp.h
gc.o: interrupt.h
gc.o: ./signal.h
gc.o: validate.h
gc.o: lispregs.h
globals.o: globals.c
globals.o: lisp.h
globals.o: ldb.h
globals.o: globals.h
globals.o: lisp.h
interrupt.o: interrupt.c
interrupt.o: ./signal.h
interrupt.o: lisp.h
interrupt.o: ldb.h
interrupt.o: globals.h
interrupt.o: lisp.h
interrupt.o: lispregs.h
interrupt.o: interrupt.h
interrupt.o: ./signal.h
interrupt.o: validate.h
ldb.o: ldb.c
ldb.o: ldb.h
ldb.o: lisp.h
ldb.o: alloc.h
ldb.o: vars.h
ldb.o: globals.h
ldb.o: lisp.h
monitor.o: monitor.c
monitor.o: ./signal.h
monitor.o: ldb.h
monitor.o: lisp.h
monitor.o: globals.h
monitor.o: lisp.h
monitor.o: vars.h
monitor.o: parse.h
monitor.o: interrupt.h
monitor.o: ./signal.h
monitor.o: lispregs.h
os.o: os.c
os.o: ldb.h
os.o: os.h
os.o: ldb.h
pager.o: pager.c
pager.o: pager.h
pagerlog.o: pagerlog.c
parse.o: parse.c
parse.o: ./signal.h
parse.o: ldb.h
parse.o: lisp.h
parse.o: globals.h
parse.o: lisp.h
parse.o: vars.h
parse.o: parse.h
parse.o: interrupt.h
parse.o: ./signal.h
parse.o: lispregs.h
print.o: print.c
print.o: ldb.h
print.o: print.h
print.o: lisp.h
print.o: vars.h
purify.o: purify.c
purify.o: lisp.h
purify.o: ldb.h
purify.o: os.h
purify.o: ldb.h
purify.o: globals.h
purify.o: lisp.h
purify.o: validate.h
purify.o: interrupt.h
purify.o: ./signal.h
purify.o: gc.h
purify.o: lisp.h
regnames.o: regnames.c
regnames.o: lispregs.h
save.o: save.c
save.o: ./signal.h
save.o: lisp.h
save.o: ldb.h
save.o: core.h
save.o: globals.h
save.o: lisp.h
save.o: lispregs.h
search.o: search.c
search.o: lisp.h
search.o: ldb.h
socket.o: socket.c
test.o: test.c
test.o: ./signal.h
test.o: lisp.h
test.o: ldb.h
validate.o: validate.c
validate.o: lisp.h
validate.o: os.h
validate.o: ldb.h
validate.o: globals.h
validate.o: lisp.h
validate.o: validate.h
vars.o: vars.c
vars.o: ldb.h
vars.o: lisp.h
vars.o: vars.h
version.o: version.c
