#!/bin/csh -fx
#
#  do-worldbuild -- script to run worldbuild
#
# $Header: /Volumes/share2/src/cmucl/cvs2git/cvsroot/src/tools/Attic/do-worldbuild,v 1.2 1991/12/13 10:32:28 wlott Exp $

if ($#argv) then
	set subdir = $argv[1]
else
	set subdir = alpha
endif

set dest = /afs/cs/project/clisp/build/@sys/$subdir
set src = /afs/cs/project/clisp/src/$subdir

if ($?LISP) then
	set lisp = "$LISP"
else
	set lisp = lisp
endif

$lisp -noinit << EOF
(setf (search-list "target:") '("$dest/" "$src/"))
(load "target:tools/setup")
(load "target:compiler/generic/genesis")
(load "target:tools/worldbuild")
(quit)
EOF
