#!/bin/csh -fx
#
# $Header: /Volumes/share2/src/cmucl/cvs2git/cvsroot/src/tools/Attic/inst-lisp,v 1.11 1995/02/17 12:08:09 wlott Exp $
#
# Utility for installing CMU CL systems in the AFS release area.
#

if ($#argv > 0) then
	set subdir = $argv[1]
else
	set subdir = alpha
endif

if ($#argv > 1) then
	set destver = $argv[2]
else
	set destver = alpha
endif

set src = /afs/cs/project/clisp/build/@sys/$subdir
set dst = /afs/cs/project/clisp/releases/${destver}/@sys

rm -f $dst/cmucl
rm -f $dst/lisp.core
rm -f $dst/site-init.*
rm -f $dst/motifd
rm -f $dst/spell-dictionary.bin
rm -f $dst/internals.h

cp -p $src/lisp/lisp $dst/cmucl
cp -p $src/lisp/internals.h $dst
cp -p lisp.core $dst/lisp.core
cp -p $src/code/cmu-site.*f $dst/site-init.fasl
cp -p $src/motif/server/motifd $dst
cp -p $src/hemlock/spell-dictionary.bin $dst
