#!/bin/csh -fx
#
# $Header: /Volumes/share2/src/cmucl/cvs2git/cvsroot/src/tools/Attic/inst-lisp,v 1.3 1992/05/27 18:13:12 wlott Exp $
#
# Utility for installing an alpha core.
#

if ($#argv) then
	set subdir = $argv[1]
else
	set subdir = alpha
endif

set src = /afs/cs/project/clisp/build/@sys/$subdir
set dst = /afs/cs/project/clisp-3/alphas/@sys

rm -f $dst/lisp $dst/lisp.core
cp -p $src/ldb/ldb $dst/lisp
cp -p lisp.core $dst/lisp.core
