#!/bin/csh -f
#
#  mk-lisp -- script for building full lisp cores.
#
# $Header: /Volumes/share2/src/cmucl/cvs2git/cvsroot/src/tools/Attic/mk-lisp,v 1.4 1991/04/20 22:44:05 wlott Exp $

if ($#argv) then
	set subdir = $argv[1]
	set features = ($argv[2-])
else
	set subdir = alpha
	set features = ()
endif

set lisp = /afs/cs/project/clisp/new-compiler/@sys/$subdir

if (-e $lisp/ldb/kernel.core) then
	set core = $lisp/ldb/kernel.core
else
	if (-e /usr/tmp/kernel.core) then
		set core = /usr/tmp/kernel.core
	else
		echo 'Can\'t find the kernel.core'
	endif
endif

set date = `/bin/date | awk '{print $2 "-" $3 "-" $6}'`

# set a bunch of random env vars to fill up space.
setenv FOO XXXXXXXXXXXXXXXX
setenv FOO $FOO$FOO$FOO$FOO
setenv FOO $FOO$FOO$FOO$FOO
setenv BAR $FOO
setenv BAZ $FOO
setenv ACK $FOO
setenv RAZ $FOO
setenv GORP $FOO

echo Building lisp.core dated $date from the \`\`$subdir\'\' subdir.

$lisp/ldb/ldb -core $core << EOF
(setf *features* (append '($features) *features*))
(setf (search-list "lisp:") '("$lisp/"))
(in-package "USER")
(load (open "lisp:tools/worldload.lisp"))
$date
$date
$date
(quit)
EOF

echo 
