#!/bin/csh -f

if ($?argv != 4) then
	echo usage: mk-release dst-sys dst-release src-sys src-release
	exit 1
endif

set dstsys = $argv[1]
set dstrelease = $argv[2]
set srcsys = $argv[3]
set srcrelease = $argv[4]

cd /afs/cs/misc/cmucl/$dstsys/$dstrelease
if ($status) then
	echo "Can't build /afs/cs/misc/cmucl/$dstsys/$dstrelease"
	exit 1
endif

set clisp = /afs/cs.cmu.edu/project/clisp
set src = $clisp/releases/$srcrelease/$srcsys

echo "Building $cwd from $src"

rm -rf README bin lib man doc

ln -s $clisp/general-info/cmu-README.txt README
mkdir bin
mkdir lib
if ($srcsys == "hp700_ux90") then
	ln -s $src/cmucl lib/cmucl.orig
	ln -s $src/hpux-startup bin/cmucl
else
	ln -s $src/cmucl bin/cmucl
endif
ln -s cmucl bin/lisp
ln -s $clisp/etc/* lib
ln -s $clisp/releases/$srcrelease/common/* lib
ln -s $src/{*.core,mot*,site-init.*,spell*} lib
mkdir doc
ln -s $clisp/general-info/bugs.txt doc
ln -s $clisp/docs/cmu-user/cmu-user.info doc
ln -s $clisp/docs/cmu-user/cmu-user.info-1 doc
ln -s $clisp/docs/cmu-user/cmu-user.info-2 doc
ln -s $clisp/docs/cmu-user/cmu-user.info-3 doc
ln -s $clisp/docs/cmu-user/cmu-user.info-4 doc
ln -s $clisp/docs/cmu-user/cmu-user.info-5 doc
ln -s $clisp/docs/cmu-user/cmu-user.info-6 doc
ln -s $clisp/docs/cmu-user/cmu-user.info-7 doc
ln -s $clisp/docs/cmu-user/cmu-user.info-8 doc
ln -s $clisp/docs/cmu-user/cmu-user.info-9 doc
ln -s $clisp/docs/cmu-user/cmu-user.ps doc
ln -s $clisp/docs/hem/cim/cim.ps doc/hemlock-cim.ps
ln -s $clisp/docs/hem/user/user.ps doc/hemlock-user.ps
ln -s $clisp/docs/interface/internals.doc doc/motif-internals.doc
ln -s $clisp/docs/interface/toolkit.doc doc/motif-toolkit.doc
ln -s $clisp/general-info/$srcrelease-release-notes.txt doc/release-notes.txt
ln -s $src/internals.h doc
mkdir man
mkdir man/man1
ln -s $clisp/general-info/cmucl.1 man/man1
ln -s $clisp/general-info/lisp.1 man/man1
