;;; -*- Package: ERRNO -*-
;;;
;;; **********************************************************************
;;; This code was written as part of the CMU Common Lisp project at
;;; Carnegie Mellon University, and has been placed in the public domain.
;;;
(ext:file-comment
  "$Header: src/code/errno.lisp $")
;;;
;;; **********************************************************************
;;;
;;; This file contains the definition of UNIX errno values from errno.h.
;;;
(in-package "UNIX")
(intl:textdomain "cmucl-unix")

;;;; Errno stuff.

;;; 
;;; From <errno.h>
;;; 
(defconstant ESUCCESS 0)
;;; The following values are autogenerated via bin/create-errno.sh
;;; DO NOT EDIT this file.  Update the templates instead.
